// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Auth service

func NewAuthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Auth service

type AuthService interface {
	// Token
	VerifyToken(ctx context.Context, in *Token, opts ...client.CallOption) (*BoolResponse, error)
	GetTokenContent(ctx context.Context, in *Token, opts ...client.CallOption) (*TokenContent, error)
	// User
	GetUsers(ctx context.Context, in *Ids, opts ...client.CallOption) (*Users, error)
	// Product
	GetProducts(ctx context.Context, in *Ids, opts ...client.CallOption) (*Products, error)
	// Group
	GetGroups(ctx context.Context, in *Ids, opts ...client.CallOption) (*Groups, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) VerifyToken(ctx context.Context, in *Token, opts ...client.CallOption) (*BoolResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.VerifyToken", in)
	out := new(BoolResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetTokenContent(ctx context.Context, in *Token, opts ...client.CallOption) (*TokenContent, error) {
	req := c.c.NewRequest(c.name, "Auth.GetTokenContent", in)
	out := new(TokenContent)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetUsers(ctx context.Context, in *Ids, opts ...client.CallOption) (*Users, error) {
	req := c.c.NewRequest(c.name, "Auth.GetUsers", in)
	out := new(Users)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetProducts(ctx context.Context, in *Ids, opts ...client.CallOption) (*Products, error) {
	req := c.c.NewRequest(c.name, "Auth.GetProducts", in)
	out := new(Products)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetGroups(ctx context.Context, in *Ids, opts ...client.CallOption) (*Groups, error) {
	req := c.c.NewRequest(c.name, "Auth.GetGroups", in)
	out := new(Groups)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	// Token
	VerifyToken(context.Context, *Token, *BoolResponse) error
	GetTokenContent(context.Context, *Token, *TokenContent) error
	// User
	GetUsers(context.Context, *Ids, *Users) error
	// Product
	GetProducts(context.Context, *Ids, *Products) error
	// Group
	GetGroups(context.Context, *Ids, *Groups) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		VerifyToken(ctx context.Context, in *Token, out *BoolResponse) error
		GetTokenContent(ctx context.Context, in *Token, out *TokenContent) error
		GetUsers(ctx context.Context, in *Ids, out *Users) error
		GetProducts(ctx context.Context, in *Ids, out *Products) error
		GetGroups(ctx context.Context, in *Ids, out *Groups) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) VerifyToken(ctx context.Context, in *Token, out *BoolResponse) error {
	return h.AuthHandler.VerifyToken(ctx, in, out)
}

func (h *authHandler) GetTokenContent(ctx context.Context, in *Token, out *TokenContent) error {
	return h.AuthHandler.GetTokenContent(ctx, in, out)
}

func (h *authHandler) GetUsers(ctx context.Context, in *Ids, out *Users) error {
	return h.AuthHandler.GetUsers(ctx, in, out)
}

func (h *authHandler) GetProducts(ctx context.Context, in *Ids, out *Products) error {
	return h.AuthHandler.GetProducts(ctx, in, out)
}

func (h *authHandler) GetGroups(ctx context.Context, in *Ids, out *Groups) error {
	return h.AuthHandler.GetGroups(ctx, in, out)
}
