// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenContent struct {
	Ok                   bool       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UserId               int32      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string     `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	IsSuperuser          bool       `protobuf:"varint,5,opt,name=is_superuser,json=isSuperuser,proto3" json:"is_superuser,omitempty"`
	Department           []string   `protobuf:"bytes,6,rep,name=department,proto3" json:"department,omitempty"`
	Roles                []string   `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	Products             []*Product `protobuf:"bytes,8,rep,name=products,proto3" json:"products,omitempty"`
	OwnProducts          []*Product `protobuf:"bytes,9,rep,name=own_products,json=ownProducts,proto3" json:"own_products,omitempty"`
	Groups               []*Group   `protobuf:"bytes,10,rep,name=groups,proto3" json:"groups,omitempty"`
	OwnGroups            []*Group   `protobuf:"bytes,11,rep,name=own_groups,json=ownGroups,proto3" json:"own_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TokenContent) Reset()         { *m = TokenContent{} }
func (m *TokenContent) String() string { return proto.CompactTextString(m) }
func (*TokenContent) ProtoMessage()    {}
func (*TokenContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *TokenContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenContent.Unmarshal(m, b)
}
func (m *TokenContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenContent.Marshal(b, m, deterministic)
}
func (m *TokenContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenContent.Merge(m, src)
}
func (m *TokenContent) XXX_Size() int {
	return xxx_messageInfo_TokenContent.Size(m)
}
func (m *TokenContent) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenContent.DiscardUnknown(m)
}

var xxx_messageInfo_TokenContent proto.InternalMessageInfo

func (m *TokenContent) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *TokenContent) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenContent) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenContent) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TokenContent) GetIsSuperuser() bool {
	if m != nil {
		return m.IsSuperuser
	}
	return false
}

func (m *TokenContent) GetDepartment() []string {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *TokenContent) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *TokenContent) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *TokenContent) GetOwnProducts() []*Product {
	if m != nil {
		return m.OwnProducts
	}
	return nil
}

func (m *TokenContent) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *TokenContent) GetOwnGroups() []*Group {
	if m != nil {
		return m.OwnGroups
	}
	return nil
}

type BoolMsg struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMsg) Reset()         { *m = BoolMsg{} }
func (m *BoolMsg) String() string { return proto.CompactTextString(m) }
func (*BoolMsg) ProtoMessage()    {}
func (*BoolMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *BoolMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMsg.Unmarshal(m, b)
}
func (m *BoolMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMsg.Marshal(b, m, deterministic)
}
func (m *BoolMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMsg.Merge(m, src)
}
func (m *BoolMsg) XXX_Size() int {
	return xxx_messageInfo_BoolMsg.Size(m)
}
func (m *BoolMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMsg proto.InternalMessageInfo

func (m *BoolMsg) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type NameQuery struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameQuery) Reset()         { *m = NameQuery{} }
func (m *NameQuery) String() string { return proto.CompactTextString(m) }
func (*NameQuery) ProtoMessage()    {}
func (*NameQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *NameQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameQuery.Unmarshal(m, b)
}
func (m *NameQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameQuery.Marshal(b, m, deterministic)
}
func (m *NameQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameQuery.Merge(m, src)
}
func (m *NameQuery) XXX_Size() int {
	return xxx_messageInfo_NameQuery.Size(m)
}
func (m *NameQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_NameQuery.DiscardUnknown(m)
}

var xxx_messageInfo_NameQuery proto.InternalMessageInfo

func (m *NameQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IdQuery struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdQuery) Reset()         { *m = IdQuery{} }
func (m *IdQuery) String() string { return proto.CompactTextString(m) }
func (*IdQuery) ProtoMessage()    {}
func (*IdQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *IdQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdQuery.Unmarshal(m, b)
}
func (m *IdQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdQuery.Marshal(b, m, deterministic)
}
func (m *IdQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdQuery.Merge(m, src)
}
func (m *IdQuery) XXX_Size() int {
	return xxx_messageInfo_IdQuery.Size(m)
}
func (m *IdQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IdQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IdQuery proto.InternalMessageInfo

func (m *IdQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HandoverRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId         int32    `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandoverRequest) Reset()         { *m = HandoverRequest{} }
func (m *HandoverRequest) String() string { return proto.CompactTextString(m) }
func (*HandoverRequest) ProtoMessage()    {}
func (*HandoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{5}
}

func (m *HandoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoverRequest.Unmarshal(m, b)
}
func (m *HandoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoverRequest.Marshal(b, m, deterministic)
}
func (m *HandoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoverRequest.Merge(m, src)
}
func (m *HandoverRequest) XXX_Size() int {
	return xxx_messageInfo_HandoverRequest.Size(m)
}
func (m *HandoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandoverRequest proto.InternalMessageInfo

func (m *HandoverRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HandoverRequest) GetTargetUserId() int32 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

type QueryWithPage struct {
	Query                map[string]string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Page                 uint32            `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32            `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryWithPage) Reset()         { *m = QueryWithPage{} }
func (m *QueryWithPage) String() string { return proto.CompactTextString(m) }
func (*QueryWithPage) ProtoMessage()    {}
func (*QueryWithPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{6}
}

func (m *QueryWithPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWithPage.Unmarshal(m, b)
}
func (m *QueryWithPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWithPage.Marshal(b, m, deterministic)
}
func (m *QueryWithPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithPage.Merge(m, src)
}
func (m *QueryWithPage) XXX_Size() int {
	return xxx_messageInfo_QueryWithPage.Size(m)
}
func (m *QueryWithPage) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithPage.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithPage proto.InternalMessageInfo

func (m *QueryWithPage) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryWithPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryWithPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserDepartment struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int32    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	IsOwner              bool     `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	JoinedAt             string   `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDepartment) Reset()         { *m = UserDepartment{} }
func (m *UserDepartment) String() string { return proto.CompactTextString(m) }
func (*UserDepartment) ProtoMessage()    {}
func (*UserDepartment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{7}
}

func (m *UserDepartment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDepartment.Unmarshal(m, b)
}
func (m *UserDepartment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDepartment.Marshal(b, m, deterministic)
}
func (m *UserDepartment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDepartment.Merge(m, src)
}
func (m *UserDepartment) XXX_Size() int {
	return xxx_messageInfo_UserDepartment.Size(m)
}
func (m *UserDepartment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDepartment.DiscardUnknown(m)
}

var xxx_messageInfo_UserDepartment proto.InternalMessageInfo

func (m *UserDepartment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserDepartment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDepartment) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *UserDepartment) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

func (m *UserDepartment) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

type PagedUsers struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedUsers) Reset()         { *m = PagedUsers{} }
func (m *PagedUsers) String() string { return proto.CompactTextString(m) }
func (*PagedUsers) ProtoMessage()    {}
func (*PagedUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{8}
}

func (m *PagedUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedUsers.Unmarshal(m, b)
}
func (m *PagedUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedUsers.Marshal(b, m, deterministic)
}
func (m *PagedUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedUsers.Merge(m, src)
}
func (m *PagedUsers) XXX_Size() int {
	return xxx_messageInfo_PagedUsers.Size(m)
}
func (m *PagedUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedUsers.DiscardUnknown(m)
}

var xxx_messageInfo_PagedUsers proto.InternalMessageInfo

func (m *PagedUsers) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PagedUsers) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedUsers) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedUsers) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedUsers) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedProducts struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Page                 uint32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32     `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32     `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32     `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PagedProducts) Reset()         { *m = PagedProducts{} }
func (m *PagedProducts) String() string { return proto.CompactTextString(m) }
func (*PagedProducts) ProtoMessage()    {}
func (*PagedProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{9}
}

func (m *PagedProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedProducts.Unmarshal(m, b)
}
func (m *PagedProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedProducts.Marshal(b, m, deterministic)
}
func (m *PagedProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedProducts.Merge(m, src)
}
func (m *PagedProducts) XXX_Size() int {
	return xxx_messageInfo_PagedProducts.Size(m)
}
func (m *PagedProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedProducts.DiscardUnknown(m)
}

var xxx_messageInfo_PagedProducts proto.InternalMessageInfo

func (m *PagedProducts) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *PagedProducts) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedProducts) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedProducts) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedProducts) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedGroups struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedGroups) Reset()         { *m = PagedGroups{} }
func (m *PagedGroups) String() string { return proto.CompactTextString(m) }
func (*PagedGroups) ProtoMessage()    {}
func (*PagedGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{10}
}

func (m *PagedGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedGroups.Unmarshal(m, b)
}
func (m *PagedGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedGroups.Marshal(b, m, deterministic)
}
func (m *PagedGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedGroups.Merge(m, src)
}
func (m *PagedGroups) XXX_Size() int {
	return xxx_messageInfo_PagedGroups.Size(m)
}
func (m *PagedGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedGroups.DiscardUnknown(m)
}

var xxx_messageInfo_PagedGroups proto.InternalMessageInfo

func (m *PagedGroups) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *PagedGroups) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedGroups) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedGroups) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedGroups) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type MemberUsers struct {
	Users                []*MemberUsers_MemberUser `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MemberUsers) Reset()         { *m = MemberUsers{} }
func (m *MemberUsers) String() string { return proto.CompactTextString(m) }
func (*MemberUsers) ProtoMessage()    {}
func (*MemberUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11}
}

func (m *MemberUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUsers.Unmarshal(m, b)
}
func (m *MemberUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUsers.Marshal(b, m, deterministic)
}
func (m *MemberUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUsers.Merge(m, src)
}
func (m *MemberUsers) XXX_Size() int {
	return xxx_messageInfo_MemberUsers.Size(m)
}
func (m *MemberUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUsers.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUsers proto.InternalMessageInfo

func (m *MemberUsers) GetUsers() []*MemberUsers_MemberUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type MemberUsers_MemberUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsOwner              bool     `protobuf:"varint,3,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	JoinedAt             string   `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUsers_MemberUser) Reset()         { *m = MemberUsers_MemberUser{} }
func (m *MemberUsers_MemberUser) String() string { return proto.CompactTextString(m) }
func (*MemberUsers_MemberUser) ProtoMessage()    {}
func (*MemberUsers_MemberUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11, 0}
}

func (m *MemberUsers_MemberUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUsers_MemberUser.Unmarshal(m, b)
}
func (m *MemberUsers_MemberUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUsers_MemberUser.Marshal(b, m, deterministic)
}
func (m *MemberUsers_MemberUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUsers_MemberUser.Merge(m, src)
}
func (m *MemberUsers_MemberUser) XXX_Size() int {
	return xxx_messageInfo_MemberUsers_MemberUser.Size(m)
}
func (m *MemberUsers_MemberUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUsers_MemberUser.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUsers_MemberUser proto.InternalMessageInfo

func (m *MemberUsers_MemberUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemberUsers_MemberUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MemberUsers_MemberUser) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

func (m *MemberUsers_MemberUser) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

type RoleMemberUsers struct {
	Users                []*RoleMemberUsers_MemberUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RoleMemberUsers) Reset()         { *m = RoleMemberUsers{} }
func (m *RoleMemberUsers) String() string { return proto.CompactTextString(m) }
func (*RoleMemberUsers) ProtoMessage()    {}
func (*RoleMemberUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{12}
}

func (m *RoleMemberUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMemberUsers.Unmarshal(m, b)
}
func (m *RoleMemberUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMemberUsers.Marshal(b, m, deterministic)
}
func (m *RoleMemberUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMemberUsers.Merge(m, src)
}
func (m *RoleMemberUsers) XXX_Size() int {
	return xxx_messageInfo_RoleMemberUsers.Size(m)
}
func (m *RoleMemberUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMemberUsers.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMemberUsers proto.InternalMessageInfo

func (m *RoleMemberUsers) GetUsers() []*RoleMemberUsers_MemberUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type RoleMemberUsers_MemberUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMemberUsers_MemberUser) Reset()         { *m = RoleMemberUsers_MemberUser{} }
func (m *RoleMemberUsers_MemberUser) String() string { return proto.CompactTextString(m) }
func (*RoleMemberUsers_MemberUser) ProtoMessage()    {}
func (*RoleMemberUsers_MemberUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{12, 0}
}

func (m *RoleMemberUsers_MemberUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMemberUsers_MemberUser.Unmarshal(m, b)
}
func (m *RoleMemberUsers_MemberUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMemberUsers_MemberUser.Marshal(b, m, deterministic)
}
func (m *RoleMemberUsers_MemberUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMemberUsers_MemberUser.Merge(m, src)
}
func (m *RoleMemberUsers_MemberUser) XXX_Size() int {
	return xxx_messageInfo_RoleMemberUsers_MemberUser.Size(m)
}
func (m *RoleMemberUsers_MemberUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMemberUsers_MemberUser.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMemberUsers_MemberUser proto.InternalMessageInfo

func (m *RoleMemberUsers_MemberUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleMemberUsers_MemberUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{13}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{14}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Product) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Group struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{15}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Department struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int32    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{16}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func init() {
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*TokenContent)(nil), "auth.TokenContent")
	proto.RegisterType((*BoolMsg)(nil), "auth.BoolMsg")
	proto.RegisterType((*NameQuery)(nil), "auth.NameQuery")
	proto.RegisterType((*IdQuery)(nil), "auth.IdQuery")
	proto.RegisterType((*HandoverRequest)(nil), "auth.HandoverRequest")
	proto.RegisterType((*QueryWithPage)(nil), "auth.QueryWithPage")
	proto.RegisterMapType((map[string]string)(nil), "auth.QueryWithPage.QueryEntry")
	proto.RegisterType((*UserDepartment)(nil), "auth.UserDepartment")
	proto.RegisterType((*PagedUsers)(nil), "auth.PagedUsers")
	proto.RegisterType((*PagedProducts)(nil), "auth.PagedProducts")
	proto.RegisterType((*PagedGroups)(nil), "auth.PagedGroups")
	proto.RegisterType((*MemberUsers)(nil), "auth.MemberUsers")
	proto.RegisterType((*MemberUsers_MemberUser)(nil), "auth.MemberUsers.MemberUser")
	proto.RegisterType((*RoleMemberUsers)(nil), "auth.RoleMemberUsers")
	proto.RegisterType((*RoleMemberUsers_MemberUser)(nil), "auth.RoleMemberUsers.MemberUser")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Product)(nil), "auth.Product")
	proto.RegisterType((*Group)(nil), "auth.Group")
	proto.RegisterType((*Department)(nil), "auth.Department")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 1037 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xf7, 0xd9, 0xbe, 0xf8, 0x3c, 0x67, 0x3b, 0xce, 0x26, 0x55, 0x2f, 0x06, 0x8a, 0x59, 0x78,
	0x08, 0x2d, 0x2a, 0x55, 0xa8, 0xa2, 0xa4, 0x15, 0xaa, 0x1a, 0x40, 0x26, 0x12, 0x81, 0x70, 0xe1,
	0x8f, 0xc4, 0x03, 0xd6, 0xa5, 0xb7, 0x38, 0x87, 0xed, 0x5b, 0xf7, 0x76, 0x2f, 0x91, 0xfb, 0xca,
	0x13, 0xe2, 0x81, 0x47, 0xbe, 0x06, 0x12, 0x9f, 0x82, 0x6f, 0xc3, 0x47, 0x40, 0x3b, 0xbb, 0x3e,
	0xdf, 0x39, 0x47, 0x15, 0xa2, 0xf6, 0xc9, 0x33, 0xb3, 0xb3, 0x33, 0xbf, 0xfb, 0xed, 0xfc, 0x31,
	0x74, 0x67, 0x09, 0x97, 0xfc, 0xc3, 0x20, 0x95, 0xe7, 0xf7, 0x51, 0x24, 0x75, 0x25, 0xd3, 0xb7,
	0xc0, 0xfe, 0x86, 0x8f, 0x59, 0x4c, 0xb6, 0xc0, 0x96, 0x4a, 0xf0, 0xac, 0xbe, 0xb5, 0xd3, 0xf4,
	0xb5, 0x42, 0xff, 0xa9, 0x42, 0x0b, 0xcf, 0x3f, 0xe1, 0xb1, 0x64, 0xb1, 0x24, 0x1d, 0xa8, 0xf2,
	0x31, 0xfa, 0x38, 0x7e, 0x95, 0x8f, 0xc9, 0x6d, 0x68, 0xa4, 0x82, 0x25, 0xc3, 0x28, 0xf4, 0xaa,
	0x7d, 0x6b, 0xc7, 0xf6, 0xd7, 0x94, 0x7a, 0x14, 0x92, 0x1e, 0x38, 0x4a, 0x8a, 0x83, 0x29, 0xf3,
	0x6a, 0x18, 0x32, 0xd3, 0x55, 0xae, 0xd9, 0x39, 0x8f, 0x99, 0x57, 0xd7, 0xb9, 0x50, 0x21, 0xef,
	0x40, 0x2b, 0x12, 0x43, 0x91, 0xce, 0x58, 0xa2, 0x3c, 0x3d, 0x1b, 0x93, 0xb8, 0x91, 0x38, 0x5d,
	0x98, 0xc8, 0x1d, 0x80, 0x90, 0xcd, 0x82, 0x44, 0x4e, 0x59, 0x2c, 0xbd, 0xb5, 0x7e, 0x6d, 0xa7,
	0xe9, 0xe7, 0x2c, 0x2a, 0x70, 0xc2, 0x27, 0x4c, 0x78, 0x0d, 0x3c, 0xd2, 0x0a, 0x79, 0x1f, 0x9c,
	0x59, 0xc2, 0xc3, 0xf4, 0x99, 0x14, 0x9e, 0xd3, 0xaf, 0xed, 0xb8, 0xbb, 0xed, 0xfb, 0x48, 0xc4,
	0x89, 0xb6, 0xfa, 0xd9, 0x31, 0x79, 0x00, 0x2d, 0x7e, 0x19, 0x0f, 0x33, 0xf7, 0x66, 0x99, 0xbb,
	0xcb, 0x2f, 0xe3, 0x93, 0xc5, 0x8d, 0x77, 0x61, 0x6d, 0x94, 0xf0, 0x74, 0x26, 0x3c, 0x40, 0x5f,
	0x57, 0xfb, 0x0e, 0x94, 0xcd, 0x37, 0x47, 0xe4, 0x2e, 0x80, 0x0a, 0x6b, 0x1c, 0xdd, 0xab, 0x8e,
	0x4d, 0x7e, 0x19, 0xa3, 0x24, 0xe8, 0x36, 0x34, 0x0e, 0x39, 0x9f, 0x1c, 0x8b, 0xd1, 0x2a, 0xd9,
	0xf4, 0x6d, 0x68, 0x7e, 0x19, 0x4c, 0xd9, 0xd7, 0x29, 0x4b, 0xe6, 0x84, 0x40, 0x1d, 0xc9, 0xd5,
	0xef, 0x85, 0xb2, 0xba, 0x7b, 0x14, 0xea, 0xe3, 0x0e, 0x54, 0xa3, 0x10, 0x0f, 0x6d, 0xbf, 0x1a,
	0x85, 0xf4, 0x04, 0xd6, 0x3f, 0x0f, 0xe2, 0x90, 0x5f, 0xb0, 0xc4, 0x67, 0xcf, 0x53, 0x26, 0x64,
	0xfe, 0xed, 0xac, 0xc2, 0xdb, 0xbd, 0x07, 0x1d, 0x19, 0x24, 0x23, 0x26, 0x87, 0xc5, 0xb7, 0x6d,
	0x69, 0xeb, 0xb7, 0xe8, 0x45, 0xff, 0xb4, 0xa0, 0x8d, 0xb9, 0xbe, 0x8f, 0xe4, 0xf9, 0x49, 0x30,
	0x62, 0xe4, 0x21, 0xd8, 0xcf, 0x95, 0xc1, 0xb3, 0xf0, 0x0b, 0xef, 0xe8, 0x2f, 0x2c, 0xf8, 0x68,
	0xed, 0xb3, 0x58, 0x26, 0x73, 0x5f, 0x3b, 0xab, 0x0f, 0x99, 0x05, 0x23, 0x86, 0x39, 0xda, 0x3e,
	0xca, 0xe4, 0x0d, 0x68, 0xaa, 0xdf, 0xa1, 0x88, 0x5e, 0xe8, 0xf2, 0x69, 0xfb, 0x8e, 0x32, 0x9c,
	0x46, 0x2f, 0x58, 0x6f, 0x1f, 0x60, 0x19, 0x85, 0x74, 0xa1, 0x36, 0x66, 0x73, 0x43, 0x83, 0x12,
	0x55, 0x15, 0x5c, 0x04, 0x93, 0x54, 0x47, 0x6c, 0xfa, 0x5a, 0x79, 0x54, 0xdd, 0xb7, 0xe8, 0xaf,
	0x16, 0x74, 0x14, 0xfa, 0x4f, 0x97, 0x25, 0xb3, 0xc2, 0x53, 0x46, 0x6b, 0x75, 0x49, 0xab, 0x46,
	0x93, 0xb0, 0x58, 0x2a, 0x2a, 0x6a, 0xe8, 0xea, 0x68, 0xc3, 0x51, 0x48, 0xb6, 0xc1, 0x89, 0xc4,
	0x90, 0x5f, 0xc6, 0x2c, 0xc1, 0x7a, 0x76, 0xfc, 0x46, 0x24, 0xbe, 0x52, 0xaa, 0xba, 0xf7, 0x33,
	0x8f, 0x62, 0x16, 0x0e, 0x03, 0x89, 0xe5, 0xdc, 0xf4, 0x1d, 0x6d, 0x78, 0x2a, 0xe9, 0x6f, 0x16,
	0x80, 0x62, 0x24, 0x54, 0x80, 0x04, 0xe9, 0x83, 0xad, 0xc8, 0x16, 0x86, 0x3b, 0xd0, 0xdc, 0xa9,
	0x33, 0x5f, 0x1f, 0x94, 0xf2, 0xa4, 0x3a, 0x29, 0x18, 0x31, 0x61, 0x38, 0xd2, 0x4a, 0x91, 0xbd,
	0x7a, 0x91, 0x3d, 0xdd, 0xe8, 0x32, 0x98, 0x20, 0xa0, 0xb6, 0xaf, 0x15, 0xfa, 0x87, 0x05, 0x6d,
	0x44, 0x93, 0x15, 0x76, 0xbe, 0x6b, 0xac, 0x97, 0x77, 0xcd, 0x6b, 0x45, 0xf6, 0xbb, 0x05, 0x2e,
	0x22, 0xd3, 0xfd, 0x91, 0x6b, 0x38, 0xeb, 0xbf, 0x1b, 0xee, 0xb5, 0x22, 0xfa, 0xcb, 0x02, 0xf7,
	0x98, 0x4d, 0xcf, 0x58, 0xa2, 0x9f, 0x6e, 0x77, 0xf1, 0x74, 0x36, 0x02, 0x7a, 0x53, 0x03, 0xca,
	0x79, 0xe4, 0x64, 0xf3, 0x98, 0xbd, 0x19, 0xc0, 0xd2, 0x78, 0xa5, 0x08, 0xf3, 0xc3, 0xb3, 0xba,
	0x32, 0x3c, 0xf3, 0xf5, 0x56, 0x7b, 0x49, 0xbd, 0xd5, 0x57, 0xea, 0xed, 0x17, 0x0b, 0xd6, 0x7d,
	0x3e, 0x61, 0x79, 0xe4, 0x7b, 0xc5, 0xa2, 0xeb, 0x6b, 0xe4, 0x2b, 0x5e, 0x25, 0xe8, 0xf7, 0x6f,
	0x8a, 0x9e, 0xfe, 0x08, 0xf5, 0xff, 0xfd, 0xc5, 0x5b, 0x60, 0xb3, 0x69, 0x10, 0x4d, 0xcc, 0x1e,
	0xd1, 0x4a, 0xf9, 0x12, 0xa1, 0x43, 0x68, 0x98, 0xfa, 0xbc, 0x56, 0x67, 0x6f, 0x81, 0x1d, 0x4c,
	0xa2, 0x40, 0x2c, 0x42, 0xa3, 0xa2, 0xc0, 0x84, 0x91, 0x08, 0xce, 0x26, 0x2c, 0x34, 0x2d, 0x9d,
	0xe9, 0xf4, 0x1e, 0xd8, 0x58, 0x6a, 0xd7, 0x09, 0x4f, 0x8f, 0x01, 0x5e, 0xe1, 0xa8, 0xd9, 0xfd,
	0xbb, 0x01, 0xee, 0xd3, 0x54, 0x9e, 0x9f, 0xb2, 0xe4, 0x22, 0x7a, 0xc6, 0xc8, 0x3d, 0x70, 0xbf,
	0x63, 0x49, 0xf4, 0xd3, 0x5c, 0xaf, 0x70, 0xd3, 0x09, 0xa8, 0xf4, 0x4c, 0xb3, 0x9a, 0x55, 0x42,
	0x2b, 0xe4, 0x21, 0xac, 0x0f, 0x98, 0x2c, 0x2c, 0xf3, 0xc2, 0x05, 0x92, 0x53, 0x8c, 0x03, 0xad,
	0x90, 0xbb, 0xe0, 0x0e, 0xf4, 0xc4, 0x3f, 0x9c, 0x1f, 0x85, 0xc4, 0x44, 0x35, 0x4b, 0xa6, 0x97,
	0x9b, 0x52, 0xb4, 0x42, 0x0e, 0xa0, 0x83, 0x8d, 0xfa, 0x45, 0x24, 0xa4, 0xae, 0xaf, 0xcd, 0x92,
	0x0d, 0xd0, 0xeb, 0x9a, 0x31, 0x92, 0xcd, 0x3e, 0x5a, 0x21, 0x8f, 0x60, 0xc3, 0xa4, 0xc9, 0xf1,
	0xb5, 0x92, 0x6c, 0x6b, 0x99, 0x6c, 0xe9, 0x44, 0x2b, 0xe4, 0x63, 0xb8, 0xbd, 0xc8, 0xb8, 0xb4,
	0xeb, 0xfc, 0x2b, 0x11, 0x36, 0xae, 0x74, 0x26, 0xa6, 0xee, 0x1e, 0x07, 0x63, 0xa6, 0xd4, 0xc5,
	0x82, 0x24, 0xb7, 0xb4, 0xe3, 0xca, 0xc2, 0xbc, 0xca, 0xe9, 0x03, 0xe8, 0x0c, 0x98, 0x34, 0x05,
	0x57, 0x46, 0x50, 0x71, 0x64, 0xd2, 0x0a, 0x79, 0x02, 0x1b, 0x19, 0x47, 0xd9, 0xa8, 0x2d, 0xa5,
	0x69, 0x33, 0x47, 0xd3, 0xc2, 0x93, 0x56, 0xc8, 0x1e, 0x74, 0x73, 0x77, 0xaf, 0xff, 0x99, 0x7b,
	0xc8, 0xf0, 0x92, 0xa0, 0x32, 0xb4, 0xe6, 0x65, 0x0a, 0xec, 0x1e, 0xc0, 0xa6, 0xca, 0x77, 0x13,
	0x66, 0x9f, 0xc0, 0x36, 0x42, 0xc5, 0xf2, 0xbd, 0x49, 0x80, 0x0f, 0xa0, 0x35, 0x60, 0x12, 0xdb,
	0xad, 0x0c, 0x6e, 0x7e, 0xf2, 0xd3, 0x0a, 0x79, 0x0c, 0xeb, 0x19, 0xb5, 0x66, 0x57, 0x94, 0x12,
	0xbb, 0x91, 0x23, 0xd6, 0xfc, 0xe7, 0x52, 0xdd, 0xd1, 0xc9, 0xee, 0x5d, 0x1f, 0xe0, 0x01, 0xb4,
	0xd5, 0x2d, 0x35, 0x30, 0xf5, 0xa5, 0x75, 0xed, 0x95, 0xfd, 0x4b, 0xeb, 0xdd, 0x2a, 0x1d, 0xa9,
	0xb4, 0x72, 0xd8, 0xfa, 0x01, 0xf0, 0x7f, 0xf8, 0x63, 0x75, 0x7e, 0xb6, 0x86, 0xf2, 0x47, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x2a, 0xd4, 0x94, 0xa7, 0x0b, 0x00, 0x00,
}
