// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eago_task.proto

package taskpb

import (
	_ "eago/common/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PagedTasks struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedTasks) Reset()         { *m = PagedTasks{} }
func (m *PagedTasks) String() string { return proto.CompactTextString(m) }
func (*PagedTasks) ProtoMessage()    {}
func (*PagedTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{0}
}

func (m *PagedTasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedTasks.Unmarshal(m, b)
}
func (m *PagedTasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedTasks.Marshal(b, m, deterministic)
}
func (m *PagedTasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedTasks.Merge(m, src)
}
func (m *PagedTasks) XXX_Size() int {
	return xxx_messageInfo_PagedTasks.Size(m)
}
func (m *PagedTasks) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedTasks.DiscardUnknown(m)
}

var xxx_messageInfo_PagedTasks proto.InternalMessageInfo

func (m *PagedTasks) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *PagedTasks) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedTasks) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedTasks) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedTasks) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedSchedules struct {
	Schedules            []*Schedule `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Page                 uint32      `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32      `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32      `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PagedSchedules) Reset()         { *m = PagedSchedules{} }
func (m *PagedSchedules) String() string { return proto.CompactTextString(m) }
func (*PagedSchedules) ProtoMessage()    {}
func (*PagedSchedules) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{1}
}

func (m *PagedSchedules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedSchedules.Unmarshal(m, b)
}
func (m *PagedSchedules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedSchedules.Marshal(b, m, deterministic)
}
func (m *PagedSchedules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedSchedules.Merge(m, src)
}
func (m *PagedSchedules) XXX_Size() int {
	return xxx_messageInfo_PagedSchedules.Size(m)
}
func (m *PagedSchedules) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedSchedules.DiscardUnknown(m)
}

var xxx_messageInfo_PagedSchedules proto.InternalMessageInfo

func (m *PagedSchedules) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

func (m *PagedSchedules) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedSchedules) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedSchedules) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedSchedules) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Task struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Codename             string   `protobuf:"bytes,2,opt,name=codename,proto3" json:"codename,omitempty"`
	FormalParams         string   `protobuf:"bytes,3,opt,name=formal_params,json=formalParams,proto3" json:"formal_params,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetCodename() string {
	if m != nil {
		return m.Codename
	}
	return ""
}

func (m *Task) GetFormalParams() string {
	if m != nil {
		return m.FormalParams
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Schedule struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskCodename         string   `protobuf:"bytes,2,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Expression           string   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	Timeout              int64    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Arguments            string   `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Disabled             bool     `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{3}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Schedule) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *Schedule) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Schedule) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Schedule) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Schedule) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Result struct {
	TaskCodename         string   `protobuf:"bytes,1,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Worker               string   `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	StartAt              string   `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Result) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *Result) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *Result) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *Result) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

type CallTaskReq struct {
	TaskCodename         string   `protobuf:"bytes,1,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Arguments            []byte   `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallTaskReq) Reset()         { *m = CallTaskReq{} }
func (m *CallTaskReq) String() string { return proto.CompactTextString(m) }
func (*CallTaskReq) ProtoMessage()    {}
func (*CallTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{5}
}

func (m *CallTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallTaskReq.Unmarshal(m, b)
}
func (m *CallTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallTaskReq.Marshal(b, m, deterministic)
}
func (m *CallTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallTaskReq.Merge(m, src)
}
func (m *CallTaskReq) XXX_Size() int {
	return xxx_messageInfo_CallTaskReq.Size(m)
}
func (m *CallTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallTaskReq proto.InternalMessageInfo

func (m *CallTaskReq) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *CallTaskReq) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CallTaskReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CallTaskReq) GetArguments() []byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type TaskUniqueId struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUniqueId) Reset()         { *m = TaskUniqueId{} }
func (m *TaskUniqueId) String() string { return proto.CompactTextString(m) }
func (*TaskUniqueId) ProtoMessage()    {}
func (*TaskUniqueId) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{6}
}

func (m *TaskUniqueId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUniqueId.Unmarshal(m, b)
}
func (m *TaskUniqueId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUniqueId.Marshal(b, m, deterministic)
}
func (m *TaskUniqueId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUniqueId.Merge(m, src)
}
func (m *TaskUniqueId) XXX_Size() int {
	return xxx_messageInfo_TaskUniqueId.Size(m)
}
func (m *TaskUniqueId) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUniqueId.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUniqueId proto.InternalMessageInfo

func (m *TaskUniqueId) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

type SetResultStatusReq struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResultStatusReq) Reset()         { *m = SetResultStatusReq{} }
func (m *SetResultStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetResultStatusReq) ProtoMessage()    {}
func (*SetResultStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{7}
}

func (m *SetResultStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResultStatusReq.Unmarshal(m, b)
}
func (m *SetResultStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResultStatusReq.Marshal(b, m, deterministic)
}
func (m *SetResultStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResultStatusReq.Merge(m, src)
}
func (m *SetResultStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetResultStatusReq.Size(m)
}
func (m *SetResultStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResultStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetResultStatusReq proto.InternalMessageInfo

func (m *SetResultStatusReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *SetResultStatusReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AppendTaskLogReq struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendTaskLogReq) Reset()         { *m = AppendTaskLogReq{} }
func (m *AppendTaskLogReq) String() string { return proto.CompactTextString(m) }
func (*AppendTaskLogReq) ProtoMessage()    {}
func (*AppendTaskLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{8}
}

func (m *AppendTaskLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendTaskLogReq.Unmarshal(m, b)
}
func (m *AppendTaskLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendTaskLogReq.Marshal(b, m, deterministic)
}
func (m *AppendTaskLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendTaskLogReq.Merge(m, src)
}
func (m *AppendTaskLogReq) XXX_Size() int {
	return xxx_messageInfo_AppendTaskLogReq.Size(m)
}
func (m *AppendTaskLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendTaskLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendTaskLogReq proto.InternalMessageInfo

func (m *AppendTaskLogReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *AppendTaskLogReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SrvTokenQuery struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvTokenQuery) Reset()         { *m = SrvTokenQuery{} }
func (m *SrvTokenQuery) String() string { return proto.CompactTextString(m) }
func (*SrvTokenQuery) ProtoMessage()    {}
func (*SrvTokenQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_be9fd9d528dc9070, []int{9}
}

func (m *SrvTokenQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvTokenQuery.Unmarshal(m, b)
}
func (m *SrvTokenQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvTokenQuery.Marshal(b, m, deterministic)
}
func (m *SrvTokenQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvTokenQuery.Merge(m, src)
}
func (m *SrvTokenQuery) XXX_Size() int {
	return xxx_messageInfo_SrvTokenQuery.Size(m)
}
func (m *SrvTokenQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvTokenQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SrvTokenQuery proto.InternalMessageInfo

func (m *SrvTokenQuery) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PagedTasks)(nil), "eago.task.PagedTasks")
	proto.RegisterType((*PagedSchedules)(nil), "eago.task.PagedSchedules")
	proto.RegisterType((*Task)(nil), "eago.task.Task")
	proto.RegisterType((*Schedule)(nil), "eago.task.Schedule")
	proto.RegisterType((*Result)(nil), "eago.task.Result")
	proto.RegisterType((*CallTaskReq)(nil), "eago.task.CallTaskReq")
	proto.RegisterType((*TaskUniqueId)(nil), "eago.task.TaskUniqueId")
	proto.RegisterType((*SetResultStatusReq)(nil), "eago.task.SetResultStatusReq")
	proto.RegisterType((*AppendTaskLogReq)(nil), "eago.task.AppendTaskLogReq")
	proto.RegisterType((*SrvTokenQuery)(nil), "eago.task.SrvTokenQuery")
}

func init() { proto.RegisterFile("eago_task.proto", fileDescriptor_be9fd9d528dc9070) }

var fileDescriptor_be9fd9d528dc9070 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x52, 0xdb, 0x48,
	0x10, 0xb5, 0x8c, 0x6d, 0xac, 0xb6, 0x8d, 0x77, 0x67, 0x17, 0x56, 0x88, 0x5d, 0xca, 0x25, 0x96,
	0x2a, 0x9f, 0xcc, 0x2e, 0xbb, 0x97, 0x1c, 0x72, 0x00, 0x8a, 0x4a, 0x91, 0x90, 0x2a, 0x22, 0x13,
	0x52, 0x95, 0x8b, 0x6b, 0x6c, 0x35, 0x46, 0x65, 0x49, 0x23, 0x34, 0x23, 0x08, 0x1c, 0xf3, 0x05,
	0xf9, 0x84, 0xdc, 0xf2, 0x01, 0xf9, 0x80, 0xfc, 0x5a, 0x6a, 0x66, 0x24, 0x5b, 0xd8, 0x31, 0xc5,
	0x25, 0x27, 0xe9, 0xbd, 0xee, 0x56, 0xbf, 0x79, 0x3d, 0x6a, 0x68, 0x23, 0x1d, 0xb3, 0x81, 0xa0,
	0x7c, 0xd2, 0x8b, 0x13, 0x26, 0x18, 0x31, 0x25, 0xd1, 0x93, 0x84, 0xbd, 0x35, 0x66, 0x6c, 0x1c,
	0xe0, 0x9e, 0x0a, 0x0c, 0xd3, 0xcb, 0x3d, 0x0c, 0x63, 0x71, 0xa7, 0xf3, 0xec, 0xed, 0xf9, 0xe0,
	0x6d, 0x42, 0xe3, 0x18, 0x13, 0x9e, 0xc5, 0x37, 0x47, 0x2c, 0x0c, 0x59, 0xa4, 0xe3, 0x7b, 0x1a,
	0xe8, 0x90, 0xf3, 0xc9, 0x00, 0x38, 0xa3, 0x63, 0xf4, 0xce, 0x29, 0x9f, 0x70, 0xb2, 0x0b, 0x55,
	0xd9, 0x8e, 0x5b, 0x46, 0x67, 0xa5, 0xdb, 0xd8, 0x6f, 0xf7, 0xa6, 0x0a, 0x7a, 0x32, 0xc1, 0xd5,
	0x51, 0x42, 0xa0, 0x12, 0xd3, 0x31, 0x5a, 0xe5, 0x8e, 0xd1, 0x6d, 0xb9, 0xea, 0x9d, 0xfc, 0x0e,
	0x55, 0xf9, 0xe4, 0xd6, 0x8a, 0x22, 0x35, 0x20, 0x5b, 0x60, 0xca, 0x97, 0x01, 0xf7, 0xef, 0xd1,
	0xaa, 0xa8, 0x48, 0x5d, 0x12, 0x7d, 0xff, 0x5e, 0x95, 0x08, 0x26, 0x68, 0x60, 0x55, 0x75, 0x89,
	0x02, 0xce, 0x67, 0x03, 0xd6, 0x94, 0xa4, 0xfe, 0xe8, 0x0a, 0xbd, 0x34, 0x40, 0x4e, 0xfe, 0x05,
	0x93, 0xe7, 0x20, 0x93, 0xf6, 0x5b, 0x41, 0x5a, 0x9e, 0xe8, 0xce, 0xb2, 0x7e, 0xae, 0xc4, 0x3b,
	0xa8, 0x48, 0x3b, 0xc8, 0x1a, 0x94, 0x7d, 0xcf, 0x32, 0x54, 0xa8, 0xec, 0x7b, 0xc4, 0x86, 0xfa,
	0x88, 0x79, 0x18, 0xd1, 0x50, 0x37, 0x36, 0xdd, 0x29, 0x26, 0x3b, 0xd0, 0xba, 0x64, 0x49, 0x48,
	0x83, 0x41, 0x4c, 0x13, 0x1a, 0x6a, 0x11, 0xa6, 0xdb, 0xd4, 0xe4, 0x99, 0xe2, 0x48, 0x07, 0x1a,
	0x1e, 0xf2, 0x51, 0xe2, 0xc7, 0xc2, 0x67, 0x91, 0x52, 0x63, 0xba, 0x45, 0xca, 0xf9, 0x6a, 0x40,
	0x3d, 0x3f, 0xef, 0x42, 0xff, 0x1d, 0x68, 0x49, 0x43, 0x06, 0x73, 0x22, 0x9a, 0x92, 0x3c, 0xca,
	0x85, 0x6c, 0x03, 0xe0, 0x87, 0x38, 0x41, 0xce, 0x65, 0x0b, 0xad, 0xa2, 0xc0, 0x10, 0x0b, 0x56,
	0x85, 0x1f, 0x22, 0x4b, 0x85, 0xea, 0xbf, 0xe2, 0xe6, 0x90, 0xfc, 0x09, 0x26, 0x4d, 0xc6, 0x69,
	0x88, 0x91, 0xe0, 0xca, 0x10, 0xd3, 0x9d, 0x11, 0xf2, 0xf0, 0x9e, 0xcf, 0xe9, 0x30, 0x40, 0xcf,
	0xaa, 0x75, 0x8c, 0x6e, 0xdd, 0x9d, 0x62, 0xe7, 0x8b, 0x01, 0x35, 0x17, 0x79, 0x1a, 0x88, 0x45,
	0x8d, 0xc6, 0x0f, 0x34, 0x6e, 0x40, 0x8d, 0x0b, 0x2a, 0x52, 0xae, 0x4e, 0x50, 0x75, 0x33, 0x24,
	0xf9, 0x11, 0x0d, 0x02, 0x4c, 0x32, 0xdd, 0x19, 0x92, 0xfc, 0x2d, 0x4b, 0x26, 0x98, 0x64, 0x96,
	0x65, 0x88, 0x6c, 0x42, 0x9d, 0x0b, 0x9a, 0x88, 0x01, 0x15, 0x99, 0xe0, 0x55, 0x85, 0x0f, 0x04,
	0x59, 0x87, 0x1a, 0x46, 0x9e, 0x0c, 0xd4, 0x54, 0xa0, 0x8a, 0x91, 0x77, 0x20, 0x9c, 0x8f, 0x06,
	0x34, 0x8e, 0x68, 0x10, 0xa8, 0xeb, 0x8e, 0xd7, 0x4f, 0x93, 0x5b, 0xb0, 0xac, 0xfc, 0xd0, 0xb2,
	0x65, 0x82, 0x1f, 0x58, 0x29, 0x35, 0x37, 0x0b, 0x56, 0x3a, 0xff, 0x43, 0x53, 0xf6, 0x7f, 0x1b,
	0xf9, 0xd7, 0x29, 0x9e, 0x78, 0xe4, 0x6f, 0x58, 0x53, 0x22, 0x52, 0x45, 0x0c, 0xb2, 0x99, 0x67,
	0x2a, 0xf2, 0x2c, 0xc7, 0x05, 0xd2, 0x47, 0xa1, 0x6d, 0xee, 0x2b, 0xbf, 0xe4, 0x01, 0x9e, 0x54,
	0xbb, 0xcc, 0x70, 0xc7, 0x85, 0x5f, 0x0e, 0xe2, 0x18, 0x23, 0xb5, 0x1f, 0x4e, 0xd9, 0xf8, 0xe9,
	0x5f, 0xb4, 0x60, 0x75, 0xc4, 0x22, 0x81, 0x91, 0xc8, 0x6e, 0x61, 0x0e, 0x9d, 0x5d, 0x68, 0xf5,
	0x93, 0x9b, 0x73, 0x36, 0xc1, 0xe8, 0x4d, 0x8a, 0xc9, 0x9d, 0xfc, 0xc9, 0x6e, 0x68, 0x90, 0xe6,
	0xde, 0x6a, 0xb0, 0xff, 0xad, 0x02, 0x0d, 0xd9, 0xb5, 0x8f, 0xc9, 0x8d, 0x3f, 0x42, 0xf2, 0x1c,
	0xea, 0xf9, 0x60, 0xc8, 0x46, 0xe1, 0xef, 0x2f, 0x4c, 0xcb, 0xfe, 0x63, 0x6e, 0x61, 0x4d, 0xbd,
	0x29, 0xc9, 0xf2, 0x57, 0x7e, 0x56, 0xbe, 0x2c, 0xcd, 0xde, 0xe8, 0xe9, 0x55, 0xda, 0xcb, 0x57,
	0x69, 0xef, 0x58, 0xee, 0x59, 0xa7, 0x44, 0x8e, 0xb3, 0xa5, 0x74, 0xea, 0x73, 0xa1, 0x77, 0xa5,
	0xad, 0x3f, 0x92, 0xad, 0x53, 0x75, 0x92, 0x77, 0xbe, 0xb8, 0x92, 0x59, 0xf6, 0x7a, 0xa1, 0xc1,
	0x6c, 0xbd, 0x3a, 0x25, 0xf2, 0x12, 0xda, 0x73, 0x33, 0x22, 0x7f, 0x15, 0x37, 0xd9, 0xc2, 0xfc,
	0x1e, 0x91, 0xf4, 0x0c, 0xcc, 0x17, 0x79, 0xfe, 0xf2, 0x23, 0xfd, 0x5a, 0x08, 0xe8, 0x5c, 0x25,
	0xa3, 0xf5, 0x60, 0xac, 0x64, 0xab, 0x90, 0x35, 0x3f, 0xf0, 0xe5, 0x12, 0xba, 0xc6, 0x3f, 0x06,
	0x79, 0x0d, 0x64, 0xea, 0xcc, 0x6c, 0x65, 0x3f, 0xe6, 0xce, 0xe6, 0xbc, 0x3b, 0xd3, 0x32, 0xa7,
	0x44, 0x4e, 0xa0, 0x7d, 0xc2, 0x2f, 0x68, 0xe0, 0x7b, 0xf9, 0x25, 0x21, 0x56, 0xd1, 0xa1, 0xe2,
	0xcd, 0xb1, 0xed, 0x05, 0x65, 0x87, 0x8c, 0x05, 0x17, 0xf2, 0xfe, 0x38, 0xa5, 0xc3, 0xfa, 0xfb,
	0x9a, 0xac, 0x89, 0x87, 0xc3, 0x9a, 0x8a, 0xff, 0xf7, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xc1,
	0xd7, 0x90, 0x63, 0x07, 0x00, 0x00,
}
