// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/proto/common.proto

package commonpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdQuery struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdQuery) Reset()         { *m = IdQuery{} }
func (m *IdQuery) String() string { return proto.CompactTextString(m) }
func (*IdQuery) ProtoMessage()    {}
func (*IdQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{0}
}

func (m *IdQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdQuery.Unmarshal(m, b)
}
func (m *IdQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdQuery.Marshal(b, m, deterministic)
}
func (m *IdQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdQuery.Merge(m, src)
}
func (m *IdQuery) XXX_Size() int {
	return xxx_messageInfo_IdQuery.Size(m)
}
func (m *IdQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IdQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IdQuery proto.InternalMessageInfo

func (m *IdQuery) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Id64Query struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id64Query) Reset()         { *m = Id64Query{} }
func (m *Id64Query) String() string { return proto.CompactTextString(m) }
func (*Id64Query) ProtoMessage()    {}
func (*Id64Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{1}
}

func (m *Id64Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id64Query.Unmarshal(m, b)
}
func (m *Id64Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id64Query.Marshal(b, m, deterministic)
}
func (m *Id64Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id64Query.Merge(m, src)
}
func (m *Id64Query) XXX_Size() int {
	return xxx_messageInfo_Id64Query.Size(m)
}
func (m *Id64Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Id64Query.DiscardUnknown(m)
}

var xxx_messageInfo_Id64Query proto.InternalMessageInfo

func (m *Id64Query) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NameQuery struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameQuery) Reset()         { *m = NameQuery{} }
func (m *NameQuery) String() string { return proto.CompactTextString(m) }
func (*NameQuery) ProtoMessage()    {}
func (*NameQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{2}
}

func (m *NameQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameQuery.Unmarshal(m, b)
}
func (m *NameQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameQuery.Marshal(b, m, deterministic)
}
func (m *NameQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameQuery.Merge(m, src)
}
func (m *NameQuery) XXX_Size() int {
	return xxx_messageInfo_NameQuery.Size(m)
}
func (m *NameQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_NameQuery.DiscardUnknown(m)
}

var xxx_messageInfo_NameQuery proto.InternalMessageInfo

func (m *NameQuery) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UuidQuery struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UuidQuery) Reset()         { *m = UuidQuery{} }
func (m *UuidQuery) String() string { return proto.CompactTextString(m) }
func (*UuidQuery) ProtoMessage()    {}
func (*UuidQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{3}
}

func (m *UuidQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UuidQuery.Unmarshal(m, b)
}
func (m *UuidQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UuidQuery.Marshal(b, m, deterministic)
}
func (m *UuidQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UuidQuery.Merge(m, src)
}
func (m *UuidQuery) XXX_Size() int {
	return xxx_messageInfo_UuidQuery.Size(m)
}
func (m *UuidQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_UuidQuery.DiscardUnknown(m)
}

var xxx_messageInfo_UuidQuery proto.InternalMessageInfo

func (m *UuidQuery) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IpQuery struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpQuery) Reset()         { *m = IpQuery{} }
func (m *IpQuery) String() string { return proto.CompactTextString(m) }
func (*IpQuery) ProtoMessage()    {}
func (*IpQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{4}
}

func (m *IpQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpQuery.Unmarshal(m, b)
}
func (m *IpQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpQuery.Marshal(b, m, deterministic)
}
func (m *IpQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpQuery.Merge(m, src)
}
func (m *IpQuery) XXX_Size() int {
	return xxx_messageInfo_IpQuery.Size(m)
}
func (m *IpQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IpQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IpQuery proto.InternalMessageInfo

func (m *IpQuery) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type QueryWithPage struct {
	Query                map[string]string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Page                 uint32            `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32            `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryWithPage) Reset()         { *m = QueryWithPage{} }
func (m *QueryWithPage) String() string { return proto.CompactTextString(m) }
func (*QueryWithPage) ProtoMessage()    {}
func (*QueryWithPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{5}
}

func (m *QueryWithPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWithPage.Unmarshal(m, b)
}
func (m *QueryWithPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWithPage.Marshal(b, m, deterministic)
}
func (m *QueryWithPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithPage.Merge(m, src)
}
func (m *QueryWithPage) XXX_Size() int {
	return xxx_messageInfo_QueryWithPage.Size(m)
}
func (m *QueryWithPage) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithPage.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithPage proto.InternalMessageInfo

func (m *QueryWithPage) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryWithPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryWithPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*IdQuery)(nil), "eago.common.IdQuery")
	proto.RegisterType((*Id64Query)(nil), "eago.common.Id64Query")
	proto.RegisterType((*NameQuery)(nil), "eago.common.NameQuery")
	proto.RegisterType((*UuidQuery)(nil), "eago.common.UuidQuery")
	proto.RegisterType((*IpQuery)(nil), "eago.common.IpQuery")
	proto.RegisterType((*QueryWithPage)(nil), "eago.common.QueryWithPage")
	proto.RegisterMapType((map[string]string)(nil), "eago.common.QueryWithPage.QueryEntry")
}

func init() { proto.RegisterFile("common/proto/common.proto", fileDescriptor_f2ad6aa6445208da) }

var fileDescriptor_f2ad6aa6445208da = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87, 0x70, 0xf4, 0xc0, 0x1c, 0x21, 0xee,
	0xd4, 0xc4, 0xf4, 0x7c, 0x3d, 0x88, 0x90, 0x92, 0x3c, 0x17, 0xbb, 0x67, 0x4a, 0x60, 0x69, 0x6a,
	0x51, 0xa5, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x6f, 0x10, 0x84, 0xa3, 0xa4, 0xc8, 0xc5, 0xe9, 0x99, 0x62, 0x66, 0x82, 0x45, 0x09, 0x0b, 0x92,
	0x12, 0xbf, 0xc4, 0xdc, 0x54, 0x2c, 0x4a, 0x38, 0x91, 0x94, 0x84, 0x96, 0x66, 0xa6, 0xe0, 0x53,
	0x02, 0x72, 0x49, 0x01, 0x3e, 0x05, 0xdb, 0x19, 0xb9, 0x78, 0xc1, 0xf2, 0xe1, 0x99, 0x25, 0x19,
	0x01, 0x89, 0xe9, 0xa9, 0x42, 0xd6, 0x5c, 0xac, 0x85, 0x20, 0x01, 0x09, 0x46, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x55, 0x3d, 0x24, 0x9f, 0xe9, 0xa1, 0x28, 0x85, 0xf0, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a,
	0x83, 0x20, 0x7a, 0x84, 0x84, 0xb8, 0x58, 0x0a, 0x12, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0xbe, 0x05,
	0xb3, 0x85, 0xa4, 0xb9, 0x38, 0x41, 0x74, 0x7c, 0x71, 0x66, 0x55, 0xaa, 0x04, 0x33, 0x58, 0x82,
	0x03, 0x24, 0x10, 0x9c, 0x59, 0x95, 0x2a, 0x65, 0xc1, 0xc5, 0x85, 0x30, 0x45, 0x48, 0x80, 0x8b,
	0x39, 0x3b, 0xb5, 0x12, 0xea, 0x42, 0x10, 0x13, 0xe1, 0x6a, 0x26, 0x24, 0x57, 0x5b, 0x31, 0x59,
	0x30, 0x3a, 0x09, 0x47, 0x09, 0x82, 0x5c, 0xa6, 0x8f, 0x1c, 0x27, 0x49, 0x6c, 0x60, 0xca, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xf0, 0x45, 0x67, 0xaa, 0x01, 0x00, 0x00,
}
