// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryWithPage struct {
	Query                map[string]string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Page                 uint32            `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32            `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryWithPage) Reset()         { *m = QueryWithPage{} }
func (m *QueryWithPage) String() string { return proto.CompactTextString(m) }
func (*QueryWithPage) ProtoMessage()    {}
func (*QueryWithPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{0}
}

func (m *QueryWithPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWithPage.Unmarshal(m, b)
}
func (m *QueryWithPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWithPage.Marshal(b, m, deterministic)
}
func (m *QueryWithPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithPage.Merge(m, src)
}
func (m *QueryWithPage) XXX_Size() int {
	return xxx_messageInfo_QueryWithPage.Size(m)
}
func (m *QueryWithPage) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithPage.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithPage proto.InternalMessageInfo

func (m *QueryWithPage) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryWithPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryWithPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PagedTasks struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedTasks) Reset()         { *m = PagedTasks{} }
func (m *PagedTasks) String() string { return proto.CompactTextString(m) }
func (*PagedTasks) ProtoMessage()    {}
func (*PagedTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{1}
}

func (m *PagedTasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedTasks.Unmarshal(m, b)
}
func (m *PagedTasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedTasks.Marshal(b, m, deterministic)
}
func (m *PagedTasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedTasks.Merge(m, src)
}
func (m *PagedTasks) XXX_Size() int {
	return xxx_messageInfo_PagedTasks.Size(m)
}
func (m *PagedTasks) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedTasks.DiscardUnknown(m)
}

var xxx_messageInfo_PagedTasks proto.InternalMessageInfo

func (m *PagedTasks) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *PagedTasks) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedTasks) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedTasks) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedTasks) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedSchedules struct {
	Schedules            []*Schedule `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Page                 uint32      `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32      `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32      `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PagedSchedules) Reset()         { *m = PagedSchedules{} }
func (m *PagedSchedules) String() string { return proto.CompactTextString(m) }
func (*PagedSchedules) ProtoMessage()    {}
func (*PagedSchedules) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{2}
}

func (m *PagedSchedules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedSchedules.Unmarshal(m, b)
}
func (m *PagedSchedules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedSchedules.Marshal(b, m, deterministic)
}
func (m *PagedSchedules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedSchedules.Merge(m, src)
}
func (m *PagedSchedules) XXX_Size() int {
	return xxx_messageInfo_PagedSchedules.Size(m)
}
func (m *PagedSchedules) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedSchedules.DiscardUnknown(m)
}

var xxx_messageInfo_PagedSchedules proto.InternalMessageInfo

func (m *PagedSchedules) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

func (m *PagedSchedules) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedSchedules) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedSchedules) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedSchedules) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Task struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Codename             string   `protobuf:"bytes,2,opt,name=codename,proto3" json:"codename,omitempty"`
	FormalParams         string   `protobuf:"bytes,3,opt,name=formal_params,json=formalParams,proto3" json:"formal_params,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{3}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetCodename() string {
	if m != nil {
		return m.Codename
	}
	return ""
}

func (m *Task) GetFormalParams() string {
	if m != nil {
		return m.FormalParams
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Schedule struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskCodename         string   `protobuf:"bytes,2,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Expression           string   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Arguments            string   `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Disabled             bool     `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{4}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Schedule) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *Schedule) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Schedule) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Schedule) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Schedule) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Result struct {
	TaskCodename         string   `protobuf:"bytes,1,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Worker               string   `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	StartAt              string   `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Result) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *Result) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *Result) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *Result) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

type CallTaskReq struct {
	TaskCodename         string   `protobuf:"bytes,1,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	Timeout              int32    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Arguments            []byte   `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallTaskReq) Reset()         { *m = CallTaskReq{} }
func (m *CallTaskReq) String() string { return proto.CompactTextString(m) }
func (*CallTaskReq) ProtoMessage()    {}
func (*CallTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{6}
}

func (m *CallTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallTaskReq.Unmarshal(m, b)
}
func (m *CallTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallTaskReq.Marshal(b, m, deterministic)
}
func (m *CallTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallTaskReq.Merge(m, src)
}
func (m *CallTaskReq) XXX_Size() int {
	return xxx_messageInfo_CallTaskReq.Size(m)
}
func (m *CallTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallTaskReq proto.InternalMessageInfo

func (m *CallTaskReq) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *CallTaskReq) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CallTaskReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CallTaskReq) GetArguments() []byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type TaskUniqueId struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUniqueId) Reset()         { *m = TaskUniqueId{} }
func (m *TaskUniqueId) String() string { return proto.CompactTextString(m) }
func (*TaskUniqueId) ProtoMessage()    {}
func (*TaskUniqueId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{7}
}

func (m *TaskUniqueId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUniqueId.Unmarshal(m, b)
}
func (m *TaskUniqueId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUniqueId.Marshal(b, m, deterministic)
}
func (m *TaskUniqueId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUniqueId.Merge(m, src)
}
func (m *TaskUniqueId) XXX_Size() int {
	return xxx_messageInfo_TaskUniqueId.Size(m)
}
func (m *TaskUniqueId) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUniqueId.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUniqueId proto.InternalMessageInfo

func (m *TaskUniqueId) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

type SetTaskStatusReq struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTaskStatusReq) Reset()         { *m = SetTaskStatusReq{} }
func (m *SetTaskStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetTaskStatusReq) ProtoMessage()    {}
func (*SetTaskStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{8}
}

func (m *SetTaskStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTaskStatusReq.Unmarshal(m, b)
}
func (m *SetTaskStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTaskStatusReq.Marshal(b, m, deterministic)
}
func (m *SetTaskStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTaskStatusReq.Merge(m, src)
}
func (m *SetTaskStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetTaskStatusReq.Size(m)
}
func (m *SetTaskStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTaskStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetTaskStatusReq proto.InternalMessageInfo

func (m *SetTaskStatusReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *SetTaskStatusReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AppendTaskLogReq struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendTaskLogReq) Reset()         { *m = AppendTaskLogReq{} }
func (m *AppendTaskLogReq) String() string { return proto.CompactTextString(m) }
func (*AppendTaskLogReq) ProtoMessage()    {}
func (*AppendTaskLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{9}
}

func (m *AppendTaskLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendTaskLogReq.Unmarshal(m, b)
}
func (m *AppendTaskLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendTaskLogReq.Marshal(b, m, deterministic)
}
func (m *AppendTaskLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendTaskLogReq.Merge(m, src)
}
func (m *AppendTaskLogReq) XXX_Size() int {
	return xxx_messageInfo_AppendTaskLogReq.Size(m)
}
func (m *AppendTaskLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendTaskLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendTaskLogReq proto.InternalMessageInfo

func (m *AppendTaskLogReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *AppendTaskLogReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type BoolMsg struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMsg) Reset()         { *m = BoolMsg{} }
func (m *BoolMsg) String() string { return proto.CompactTextString(m) }
func (*BoolMsg) ProtoMessage()    {}
func (*BoolMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{10}
}

func (m *BoolMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMsg.Unmarshal(m, b)
}
func (m *BoolMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMsg.Marshal(b, m, deterministic)
}
func (m *BoolMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMsg.Merge(m, src)
}
func (m *BoolMsg) XXX_Size() int {
	return xxx_messageInfo_BoolMsg.Size(m)
}
func (m *BoolMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMsg proto.InternalMessageInfo

func (m *BoolMsg) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*QueryWithPage)(nil), "task.QueryWithPage")
	proto.RegisterMapType((map[string]string)(nil), "task.QueryWithPage.QueryEntry")
	proto.RegisterType((*PagedTasks)(nil), "task.PagedTasks")
	proto.RegisterType((*PagedSchedules)(nil), "task.PagedSchedules")
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*Schedule)(nil), "task.Schedule")
	proto.RegisterType((*Result)(nil), "task.Result")
	proto.RegisterType((*CallTaskReq)(nil), "task.CallTaskReq")
	proto.RegisterType((*TaskUniqueId)(nil), "task.TaskUniqueId")
	proto.RegisterType((*SetTaskStatusReq)(nil), "task.SetTaskStatusReq")
	proto.RegisterType((*AppendTaskLogReq)(nil), "task.AppendTaskLogReq")
	proto.RegisterType((*BoolMsg)(nil), "task.BoolMsg")
}

func init() { proto.RegisterFile("proto/task.proto", fileDescriptor_5de11d747d3f16e6) }

var fileDescriptor_5de11d747d3f16e6 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcf, 0x6e, 0x13, 0x3b,
	0x14, 0xc6, 0x33, 0x49, 0x26, 0x99, 0x39, 0xc9, 0x44, 0xb9, 0xbe, 0xbd, 0x55, 0x9a, 0x8b, 0xaa,
	0xc8, 0x65, 0x91, 0x05, 0x6a, 0x51, 0xdb, 0x45, 0x05, 0xdd, 0xb4, 0x15, 0x42, 0x88, 0x22, 0x15,
	0x07, 0x84, 0xc4, 0x26, 0x72, 0x33, 0x26, 0x1d, 0x65, 0x32, 0x4e, 0xc7, 0x9e, 0x42, 0xbb, 0x64,
	0xcb, 0x86, 0x3d, 0x0f, 0xc0, 0x16, 0x89, 0x17, 0x44, 0xfe, 0x33, 0x4d, 0xa6, 0x49, 0xa5, 0x6e,
	0x58, 0x8d, 0xcf, 0x67, 0x1f, 0x9f, 0x9f, 0x3f, 0x3b, 0x27, 0xd0, 0x9e, 0xa5, 0x5c, 0xf2, 0x1d,
	0x49, 0xc5, 0x64, 0x5b, 0x0f, 0x51, 0x55, 0x8d, 0xf1, 0x2f, 0x07, 0x82, 0xb7, 0x19, 0x4b, 0xaf,
	0x3f, 0x44, 0xf2, 0xe2, 0x8c, 0x8e, 0x19, 0xda, 0x07, 0xf7, 0x52, 0x09, 0x1d, 0xa7, 0x57, 0xe9,
	0x37, 0x76, 0x37, 0xb7, 0x75, 0x4e, 0x61, 0x8d, 0x89, 0x5e, 0x24, 0x32, 0xbd, 0x26, 0x66, 0x31,
	0x42, 0x50, 0x9d, 0xd1, 0x31, 0xeb, 0x94, 0x7b, 0x4e, 0x3f, 0x20, 0x7a, 0x8c, 0xfe, 0x07, 0x5f,
	0x7d, 0x87, 0x22, 0xba, 0x61, 0x9d, 0x8a, 0x9e, 0xf0, 0x94, 0x30, 0x88, 0x6e, 0x58, 0xf7, 0x00,
	0x60, 0xbe, 0x0b, 0x6a, 0x43, 0x65, 0xc2, 0x54, 0x49, 0xa7, 0xef, 0x13, 0x35, 0x44, 0x6b, 0xe0,
	0x5e, 0xd1, 0x38, 0x33, 0x3b, 0xfa, 0xc4, 0x04, 0xcf, 0xca, 0x07, 0x0e, 0xfe, 0xe6, 0x00, 0x28,
	0x8a, 0xf0, 0x1d, 0x15, 0x13, 0x81, 0x7a, 0xe0, 0x2a, 0x42, 0x61, 0x79, 0xc1, 0xf0, 0xaa, 0x39,
	0x62, 0x26, 0x56, 0xb2, 0xad, 0x81, 0xab, 0xbe, 0xc2, 0x72, 0x99, 0xa0, 0x48, 0x5c, 0x2d, 0x12,
	0xab, 0x14, 0xc9, 0x25, 0x8d, 0x3b, 0xae, 0x49, 0xd1, 0x01, 0xfe, 0xe1, 0x40, 0x4b, 0xd3, 0x0c,
	0x46, 0x17, 0x2c, 0xcc, 0x62, 0x26, 0xd0, 0x13, 0xf0, 0x45, 0x1e, 0x58, 0xaa, 0x96, 0xa1, 0xca,
	0xd7, 0x90, 0xf9, 0x82, 0xbf, 0x4b, 0x77, 0x0d, 0x55, 0xe5, 0x04, 0x6a, 0x41, 0x39, 0x0a, 0xb5,
	0xbd, 0x2e, 0x29, 0x47, 0x21, 0xea, 0x82, 0x37, 0xe2, 0x21, 0x4b, 0xe8, 0x34, 0x37, 0xf8, 0x36,
	0x46, 0x5b, 0x10, 0x7c, 0xe2, 0xe9, 0x94, 0xc6, 0xc3, 0x19, 0x4d, 0xe9, 0xd4, 0x40, 0xf8, 0xa4,
	0x69, 0xc4, 0x33, 0xad, 0xa1, 0x1e, 0x34, 0x42, 0x26, 0x46, 0x69, 0x34, 0x93, 0x11, 0x4f, 0x34,
	0x8d, 0x4f, 0x16, 0x25, 0xfc, 0xdb, 0x01, 0x2f, 0x3f, 0xef, 0x52, 0xfd, 0x2d, 0x08, 0x94, 0x21,
	0xc3, 0x3b, 0x10, 0x4d, 0x25, 0x9e, 0xe4, 0x20, 0x9b, 0x00, 0xec, 0xcb, 0x2c, 0x65, 0x42, 0xa8,
	0x12, 0x86, 0x62, 0x41, 0x41, 0x1d, 0xa8, 0xcb, 0x68, 0xca, 0x78, 0x26, 0x75, 0x7d, 0x97, 0xe4,
	0x21, 0x7a, 0x04, 0x3e, 0x4d, 0xc7, 0xd9, 0x94, 0x25, 0x52, 0x68, 0x43, 0x7c, 0x32, 0x17, 0xd4,
	0xe1, 0xc3, 0x48, 0xd0, 0xf3, 0x98, 0x85, 0x9d, 0x5a, 0xcf, 0xe9, 0x7b, 0xe4, 0x36, 0xc6, 0x3f,
	0x1d, 0xa8, 0x11, 0x26, 0xb2, 0x58, 0x2e, 0x33, 0x3a, 0x2b, 0x18, 0xd7, 0xa1, 0x26, 0x24, 0x95,
	0x99, 0xd0, 0x27, 0x70, 0x89, 0x8d, 0x94, 0x3e, 0xa2, 0x71, 0xcc, 0x52, 0xcb, 0x6d, 0x23, 0xa5,
	0x7f, 0xe6, 0xe9, 0x84, 0xa5, 0xd6, 0x32, 0x1b, 0xa1, 0x0d, 0xf0, 0x84, 0xa4, 0xa9, 0x1c, 0x52,
	0x69, 0x81, 0xeb, 0x3a, 0x3e, 0x92, 0xe8, 0x3f, 0xa8, 0xb1, 0x24, 0x54, 0x13, 0x35, 0xf3, 0x53,
	0x60, 0x49, 0x78, 0x24, 0xf1, 0x57, 0x07, 0x1a, 0x27, 0x34, 0x8e, 0xf5, 0x4b, 0x67, 0x97, 0x0f,
	0xc3, 0x5d, 0xb0, 0xac, 0x5c, 0xb4, 0xec, 0x3e, 0xe0, 0x82, 0x95, 0x8a, 0xb9, 0xb9, 0x60, 0x25,
	0xde, 0x87, 0xa6, 0xaa, 0xff, 0x3e, 0x89, 0x2e, 0x33, 0xf6, 0x2a, 0x44, 0x8f, 0xa1, 0xa5, 0x21,
	0x32, 0x2d, 0x0c, 0xed, 0x9d, 0x5b, 0x8a, 0x7c, 0x15, 0x3e, 0x83, 0xf6, 0x80, 0x49, 0x95, 0x38,
	0xd0, 0x6e, 0x29, 0xfc, 0x07, 0x65, 0xde, 0x67, 0x37, 0x26, 0xd0, 0x3e, 0x9a, 0xcd, 0x58, 0xa2,
	0x7b, 0xc2, 0x29, 0x1f, 0x3f, 0x7c, 0xc7, 0x0e, 0xd4, 0x47, 0x3c, 0x91, 0x2c, 0x91, 0xf6, 0x0d,
	0xe6, 0x21, 0xde, 0x80, 0xfa, 0x31, 0xe7, 0xf1, 0x1b, 0x31, 0x56, 0xcf, 0x97, 0x4f, 0x74, 0xba,
	0x47, 0xca, 0x7c, 0xb2, 0xfb, 0xbd, 0x02, 0x0d, 0x8d, 0xcf, 0xd2, 0xab, 0x68, 0xa4, 0x7a, 0xa6,
	0x7f, 0x1a, 0x09, 0x69, 0x1a, 0xd2, 0xbf, 0x2b, 0x3a, 0x66, 0xb7, 0x6d, 0xc4, 0x79, 0xdf, 0xc2,
	0x25, 0x74, 0x08, 0x81, 0xca, 0x9a, 0x37, 0x8e, 0x95, 0x99, 0x6b, 0x0b, 0x99, 0xb7, 0x4b, 0x71,
	0x09, 0xed, 0x80, 0xff, 0x92, 0x49, 0xfb, 0x56, 0xd1, 0xbc, 0xeb, 0xe5, 0x27, 0xeb, 0x36, 0x8d,
	0x66, 0x56, 0xe0, 0x12, 0xda, 0x03, 0x2f, 0x7f, 0x2f, 0xe8, 0x1f, 0x33, 0xb7, 0xf0, 0x7e, 0xba,
	0x2b, 0xb6, 0xd0, 0x55, 0xbc, 0xd7, 0x91, 0x4d, 0x5a, 0x55, 0x24, 0x30, 0x9a, 0x35, 0x0a, 0x97,
	0xd0, 0x01, 0x04, 0x85, 0xbb, 0x45, 0xeb, 0xb6, 0xf5, 0xdd, 0xb9, 0xf0, 0xe5, 0xcc, 0x43, 0x08,
	0x0a, 0x77, 0x98, 0x67, 0xde, 0xbd, 0xd8, 0xa5, 0xcc, 0xbe, 0xf3, 0xd4, 0x39, 0x6e, 0x7e, 0x04,
	0xfd, 0xbf, 0xf6, 0x5c, 0xcd, 0x9d, 0xd7, 0xf4, 0x78, 0xef, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x21, 0x47, 0xe9, 0xf7, 0x06, 0x00, 0x00,
}
