// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eago_auth.proto

package authpb

import (
	_ "eago/common/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TokenContent struct {
	UserId               uint32     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string     `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string     `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	IsSuperuser          bool       `protobuf:"varint,4,opt,name=is_superuser,json=isSuperuser,proto3" json:"is_superuser,omitempty"`
	Department           []string   `protobuf:"bytes,5,rep,name=department,proto3" json:"department,omitempty"`
	Roles                []string   `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Products             []*Product `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	OwnProducts          []*Product `protobuf:"bytes,8,rep,name=own_products,json=ownProducts,proto3" json:"own_products,omitempty"`
	Groups               []*Group   `protobuf:"bytes,9,rep,name=groups,proto3" json:"groups,omitempty"`
	OwnGroups            []*Group   `protobuf:"bytes,10,rep,name=own_groups,json=ownGroups,proto3" json:"own_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TokenContent) Reset()         { *m = TokenContent{} }
func (m *TokenContent) String() string { return proto.CompactTextString(m) }
func (*TokenContent) ProtoMessage()    {}
func (*TokenContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{1}
}

func (m *TokenContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenContent.Unmarshal(m, b)
}
func (m *TokenContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenContent.Marshal(b, m, deterministic)
}
func (m *TokenContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenContent.Merge(m, src)
}
func (m *TokenContent) XXX_Size() int {
	return xxx_messageInfo_TokenContent.Size(m)
}
func (m *TokenContent) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenContent.DiscardUnknown(m)
}

var xxx_messageInfo_TokenContent proto.InternalMessageInfo

func (m *TokenContent) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenContent) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenContent) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TokenContent) GetIsSuperuser() bool {
	if m != nil {
		return m.IsSuperuser
	}
	return false
}

func (m *TokenContent) GetDepartment() []string {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *TokenContent) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *TokenContent) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *TokenContent) GetOwnProducts() []*Product {
	if m != nil {
		return m.OwnProducts
	}
	return nil
}

func (m *TokenContent) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *TokenContent) GetOwnGroups() []*Group {
	if m != nil {
		return m.OwnGroups
	}
	return nil
}

// UsersDepartment 用户所在部门的信息
type UsersDepartment struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             uint32   `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	IsOwner              bool     `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	JoinedAt             string   `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDepartment) Reset()         { *m = UsersDepartment{} }
func (m *UsersDepartment) String() string { return proto.CompactTextString(m) }
func (*UsersDepartment) ProtoMessage()    {}
func (*UsersDepartment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{2}
}

func (m *UsersDepartment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDepartment.Unmarshal(m, b)
}
func (m *UsersDepartment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDepartment.Marshal(b, m, deterministic)
}
func (m *UsersDepartment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDepartment.Merge(m, src)
}
func (m *UsersDepartment) XXX_Size() int {
	return xxx_messageInfo_UsersDepartment.Size(m)
}
func (m *UsersDepartment) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDepartment.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDepartment proto.InternalMessageInfo

func (m *UsersDepartment) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UsersDepartment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersDepartment) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *UsersDepartment) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

func (m *UsersDepartment) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

type PagedUsers struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedUsers) Reset()         { *m = PagedUsers{} }
func (m *PagedUsers) String() string { return proto.CompactTextString(m) }
func (*PagedUsers) ProtoMessage()    {}
func (*PagedUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{3}
}

func (m *PagedUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedUsers.Unmarshal(m, b)
}
func (m *PagedUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedUsers.Marshal(b, m, deterministic)
}
func (m *PagedUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedUsers.Merge(m, src)
}
func (m *PagedUsers) XXX_Size() int {
	return xxx_messageInfo_PagedUsers.Size(m)
}
func (m *PagedUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedUsers.DiscardUnknown(m)
}

var xxx_messageInfo_PagedUsers proto.InternalMessageInfo

func (m *PagedUsers) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PagedUsers) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedUsers) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedUsers) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedUsers) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedProducts struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Page                 uint32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32     `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32     `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32     `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PagedProducts) Reset()         { *m = PagedProducts{} }
func (m *PagedProducts) String() string { return proto.CompactTextString(m) }
func (*PagedProducts) ProtoMessage()    {}
func (*PagedProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{4}
}

func (m *PagedProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedProducts.Unmarshal(m, b)
}
func (m *PagedProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedProducts.Marshal(b, m, deterministic)
}
func (m *PagedProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedProducts.Merge(m, src)
}
func (m *PagedProducts) XXX_Size() int {
	return xxx_messageInfo_PagedProducts.Size(m)
}
func (m *PagedProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedProducts.DiscardUnknown(m)
}

var xxx_messageInfo_PagedProducts proto.InternalMessageInfo

func (m *PagedProducts) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *PagedProducts) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedProducts) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedProducts) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedProducts) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PagedGroups struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedGroups) Reset()         { *m = PagedGroups{} }
func (m *PagedGroups) String() string { return proto.CompactTextString(m) }
func (*PagedGroups) ProtoMessage()    {}
func (*PagedGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{5}
}

func (m *PagedGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedGroups.Unmarshal(m, b)
}
func (m *PagedGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedGroups.Marshal(b, m, deterministic)
}
func (m *PagedGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedGroups.Merge(m, src)
}
func (m *PagedGroups) XXX_Size() int {
	return xxx_messageInfo_PagedGroups.Size(m)
}
func (m *PagedGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedGroups.DiscardUnknown(m)
}

var xxx_messageInfo_PagedGroups proto.InternalMessageInfo

func (m *PagedGroups) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *PagedGroups) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedGroups) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *PagedGroups) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PagedGroups) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

// MemberUsers 成员用户-通用
type MemberUsers struct {
	Users                []*MemberUsers_MemberUser `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MemberUsers) Reset()         { *m = MemberUsers{} }
func (m *MemberUsers) String() string { return proto.CompactTextString(m) }
func (*MemberUsers) ProtoMessage()    {}
func (*MemberUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{6}
}

func (m *MemberUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUsers.Unmarshal(m, b)
}
func (m *MemberUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUsers.Marshal(b, m, deterministic)
}
func (m *MemberUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUsers.Merge(m, src)
}
func (m *MemberUsers) XXX_Size() int {
	return xxx_messageInfo_MemberUsers.Size(m)
}
func (m *MemberUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUsers.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUsers proto.InternalMessageInfo

func (m *MemberUsers) GetUsers() []*MemberUsers_MemberUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type MemberUsers_MemberUser struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsOwner              bool     `protobuf:"varint,3,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	JoinedAt             string   `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUsers_MemberUser) Reset()         { *m = MemberUsers_MemberUser{} }
func (m *MemberUsers_MemberUser) String() string { return proto.CompactTextString(m) }
func (*MemberUsers_MemberUser) ProtoMessage()    {}
func (*MemberUsers_MemberUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{6, 0}
}

func (m *MemberUsers_MemberUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUsers_MemberUser.Unmarshal(m, b)
}
func (m *MemberUsers_MemberUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUsers_MemberUser.Marshal(b, m, deterministic)
}
func (m *MemberUsers_MemberUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUsers_MemberUser.Merge(m, src)
}
func (m *MemberUsers_MemberUser) XXX_Size() int {
	return xxx_messageInfo_MemberUsers_MemberUser.Size(m)
}
func (m *MemberUsers_MemberUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUsers_MemberUser.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUsers_MemberUser proto.InternalMessageInfo

func (m *MemberUsers_MemberUser) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemberUsers_MemberUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MemberUsers_MemberUser) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

func (m *MemberUsers_MemberUser) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

// RolesMemberUsers 角色成员用户
type RolesMemberUsers struct {
	Users                []*RolesMemberUsers_MemberUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RolesMemberUsers) Reset()         { *m = RolesMemberUsers{} }
func (m *RolesMemberUsers) String() string { return proto.CompactTextString(m) }
func (*RolesMemberUsers) ProtoMessage()    {}
func (*RolesMemberUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{7}
}

func (m *RolesMemberUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolesMemberUsers.Unmarshal(m, b)
}
func (m *RolesMemberUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolesMemberUsers.Marshal(b, m, deterministic)
}
func (m *RolesMemberUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolesMemberUsers.Merge(m, src)
}
func (m *RolesMemberUsers) XXX_Size() int {
	return xxx_messageInfo_RolesMemberUsers.Size(m)
}
func (m *RolesMemberUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_RolesMemberUsers.DiscardUnknown(m)
}

var xxx_messageInfo_RolesMemberUsers proto.InternalMessageInfo

func (m *RolesMemberUsers) GetUsers() []*RolesMemberUsers_MemberUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type RolesMemberUsers_MemberUser struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolesMemberUsers_MemberUser) Reset()         { *m = RolesMemberUsers_MemberUser{} }
func (m *RolesMemberUsers_MemberUser) String() string { return proto.CompactTextString(m) }
func (*RolesMemberUsers_MemberUser) ProtoMessage()    {}
func (*RolesMemberUsers_MemberUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{7, 0}
}

func (m *RolesMemberUsers_MemberUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolesMemberUsers_MemberUser.Unmarshal(m, b)
}
func (m *RolesMemberUsers_MemberUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolesMemberUsers_MemberUser.Marshal(b, m, deterministic)
}
func (m *RolesMemberUsers_MemberUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolesMemberUsers_MemberUser.Merge(m, src)
}
func (m *RolesMemberUsers_MemberUser) XXX_Size() int {
	return xxx_messageInfo_RolesMemberUsers_MemberUser.Size(m)
}
func (m *RolesMemberUsers_MemberUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RolesMemberUsers_MemberUser.DiscardUnknown(m)
}

var xxx_messageInfo_RolesMemberUsers_MemberUser proto.InternalMessageInfo

func (m *RolesMemberUsers_MemberUser) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RolesMemberUsers_MemberUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{9}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Product) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Group struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{10}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Department struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             uint32   `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_a467f4fd1dd5e764, []int{11}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func init() {
	proto.RegisterType((*Token)(nil), "eago.auth.Token")
	proto.RegisterType((*TokenContent)(nil), "eago.auth.TokenContent")
	proto.RegisterType((*UsersDepartment)(nil), "eago.auth.UsersDepartment")
	proto.RegisterType((*PagedUsers)(nil), "eago.auth.PagedUsers")
	proto.RegisterType((*PagedProducts)(nil), "eago.auth.PagedProducts")
	proto.RegisterType((*PagedGroups)(nil), "eago.auth.PagedGroups")
	proto.RegisterType((*MemberUsers)(nil), "eago.auth.MemberUsers")
	proto.RegisterType((*MemberUsers_MemberUser)(nil), "eago.auth.MemberUsers.MemberUser")
	proto.RegisterType((*RolesMemberUsers)(nil), "eago.auth.RolesMemberUsers")
	proto.RegisterType((*RolesMemberUsers_MemberUser)(nil), "eago.auth.RolesMemberUsers.MemberUser")
	proto.RegisterType((*User)(nil), "eago.auth.User")
	proto.RegisterType((*Product)(nil), "eago.auth.Product")
	proto.RegisterType((*Group)(nil), "eago.auth.Group")
	proto.RegisterType((*Department)(nil), "eago.auth.Department")
}

func init() { proto.RegisterFile("eago_auth.proto", fileDescriptor_a467f4fd1dd5e764) }

var fileDescriptor_a467f4fd1dd5e764 = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xde, 0x4d, 0x6c, 0xc7, 0x3e, 0x4e, 0xe2, 0x66, 0xe4, 0xa6, 0x1b, 0x07, 0x50, 0x3a, 0x12,
	0xc8, 0x12, 0x92, 0x23, 0x15, 0x01, 0x45, 0xaa, 0x90, 0x92, 0x52, 0x4c, 0x04, 0x2d, 0x61, 0xc3,
	0x8f, 0xc4, 0x05, 0xd6, 0x3a, 0x7b, 0xba, 0x59, 0xf0, 0xee, 0xac, 0x76, 0x66, 0x1b, 0xa5, 0x8f,
	0xd0, 0x2b, 0x2e, 0xb8, 0xe4, 0x41, 0x78, 0x15, 0xde, 0x83, 0x07, 0x40, 0x73, 0x66, 0xbd, 0x1e,
	0x3b, 0xae, 0x09, 0x81, 0xde, 0xcd, 0xf9, 0xfb, 0xf6, 0x3b, 0x3f, 0x73, 0x66, 0xa1, 0x83, 0x41,
	0x24, 0x46, 0x41, 0xa1, 0x2e, 0x06, 0x59, 0x2e, 0x94, 0x60, 0x2d, 0xad, 0x18, 0x68, 0x45, 0x6f,
	0x3f, 0x12, 0x22, 0x9a, 0xe0, 0x21, 0x19, 0xc6, 0xc5, 0xf3, 0x43, 0x4c, 0x32, 0x75, 0x65, 0xfc,
	0x7a, 0x7b, 0xe7, 0x22, 0x49, 0x44, 0x6a, 0x8c, 0x87, 0x46, 0x30, 0x26, 0xfe, 0x36, 0xd4, 0xbf,
	0x15, 0xbf, 0x60, 0xca, 0xba, 0x50, 0x7f, 0x11, 0x4c, 0x0a, 0xf4, 0xdc, 0x03, 0xb7, 0xdf, 0xf2,
	0x8d, 0xc0, 0xff, 0x5a, 0x83, 0x4d, 0xb2, 0x3f, 0x16, 0xa9, 0xc2, 0x54, 0xb1, 0x7b, 0xb0, 0x51,
	0x48, 0xcc, 0x47, 0x71, 0x48, 0x8e, 0x5b, 0x7e, 0x43, 0x8b, 0x27, 0x21, 0xeb, 0x41, 0x53, 0x9f,
	0xd2, 0x20, 0x41, 0x6f, 0x8d, 0x20, 0x2a, 0x59, 0x63, 0x67, 0x17, 0x22, 0x45, 0x6f, 0xdd, 0x60,
	0x93, 0xc0, 0xee, 0xc3, 0x66, 0x2c, 0x47, 0xb2, 0xc8, 0x30, 0xd7, 0x9e, 0x5e, 0xed, 0xc0, 0xed,
	0x37, 0xfd, 0x76, 0x2c, 0xcf, 0xa6, 0x2a, 0xf6, 0x0e, 0x40, 0x88, 0x59, 0x90, 0xab, 0x04, 0x53,
	0xe5, 0xd5, 0x0f, 0xd6, 0xfb, 0x2d, 0xdf, 0xd2, 0x68, 0xe0, 0x5c, 0x4c, 0x50, 0x7a, 0x0d, 0x32,
	0x19, 0x81, 0x0d, 0xa0, 0x99, 0xe5, 0x22, 0x2c, 0xce, 0x95, 0xf4, 0x36, 0x0e, 0xd6, 0xfb, 0xed,
	0x07, 0x6c, 0x50, 0x55, 0x6a, 0x70, 0x6a, 0x4c, 0x7e, 0xe5, 0xc3, 0x3e, 0x84, 0x4d, 0x71, 0x99,
	0x8e, 0xaa, 0x98, 0xe6, 0x6b, 0x63, 0xda, 0xe2, 0x32, 0x3d, 0x9d, 0x86, 0xf5, 0xa1, 0x11, 0xe5,
	0xa2, 0xc8, 0xa4, 0xd7, 0xa2, 0x80, 0x3b, 0x56, 0xc0, 0x50, 0x1b, 0xfc, 0xd2, 0xce, 0x0e, 0x01,
	0xf4, 0x07, 0x4a, 0x6f, 0x78, 0x8d, 0x77, 0x4b, 0x5c, 0xa6, 0x74, 0x92, 0xfc, 0x95, 0x0b, 0x9d,
	0xef, 0x24, 0xe6, 0xf2, 0xb3, 0x59, 0xae, 0xdb, 0xb0, 0x56, 0x15, 0x7d, 0x2d, 0x0e, 0x19, 0x83,
	0x9a, 0x55, 0x6c, 0x3a, 0xb3, 0x7d, 0x68, 0x65, 0x41, 0x8e, 0xa9, 0xd2, 0xfd, 0x59, 0x27, 0xd7,
	0xa6, 0x51, 0x9c, 0x84, 0x6c, 0x0f, 0x9a, 0xb1, 0x1c, 0x89, 0xcb, 0xb4, 0xaa, 0xf5, 0x46, 0x2c,
	0xbf, 0xd6, 0xa2, 0x8e, 0xfb, 0x59, 0xc4, 0x29, 0x86, 0xa3, 0x40, 0x97, 0x99, 0xba, 0x67, 0x14,
	0x47, 0x8a, 0xff, 0xea, 0x02, 0x9c, 0x06, 0x11, 0x86, 0xc4, 0x88, 0xbd, 0x0b, 0x75, 0xdd, 0x1b,
	0xe9, 0xb9, 0x94, 0x47, 0xc7, 0xca, 0x43, 0x3b, 0xf8, 0xc6, 0xaa, 0xe9, 0x65, 0x41, 0x64, 0xe8,
	0x6d, 0xf9, 0x74, 0xa6, 0x39, 0x08, 0x22, 0x94, 0x25, 0x35, 0x23, 0x18, 0xd2, 0x11, 0x8e, 0x64,
	0xfc, 0x12, 0x89, 0x18, 0x91, 0x8e, 0xf0, 0x2c, 0x7e, 0x49, 0x21, 0x4a, 0xa8, 0x60, 0x42, 0xac,
	0xb6, 0x7c, 0x23, 0xf0, 0xdf, 0x5d, 0xd8, 0x22, 0x4a, 0x55, 0x33, 0xec, 0x9e, 0xbb, 0x37, 0xe8,
	0xf9, 0x1b, 0xa5, 0xf7, 0x9b, 0x0b, 0x6d, 0xa2, 0x67, 0xda, 0x69, 0x4d, 0x8a, 0xfb, 0x0f, 0x93,
	0xf2, 0x46, 0x69, 0xfd, 0xe1, 0x42, 0xfb, 0x29, 0x26, 0x63, 0xcc, 0x4d, 0x27, 0x3f, 0x9e, 0x76,
	0xb2, 0x4e, 0xac, 0xee, 0x5b, 0xac, 0x2c, 0x37, 0xeb, 0x5c, 0xf6, 0xb6, 0x97, 0x01, 0xcc, 0x94,
	0xd7, 0x06, 0x73, 0xd5, 0x26, 0xb0, 0x67, 0x70, 0x7d, 0xc5, 0x0c, 0xd6, 0x16, 0x66, 0xf0, 0x95,
	0x0b, 0x77, 0x7c, 0x7d, 0xb9, 0x6d, 0xfe, 0x8f, 0xe6, 0x27, 0xf1, 0x3d, 0x8b, 0xff, 0xa2, 0xef,
	0x92, 0x24, 0x1e, 0xde, 0x36, 0x09, 0xfe, 0x13, 0xd4, 0xfe, 0x75, 0xe2, 0x5d, 0xa8, 0x63, 0x12,
	0xc4, 0x93, 0xe9, 0x0a, 0x24, 0x61, 0xb6, 0x18, 0x6b, 0xd6, 0x62, 0xe4, 0x23, 0xd8, 0x28, 0x07,
	0xf6, 0x46, 0x97, 0xbe, 0x0b, 0xf5, 0x60, 0x12, 0x07, 0x72, 0x0a, 0x4d, 0x82, 0x26, 0x13, 0xc6,
	0x32, 0x18, 0x4f, 0x30, 0x2c, 0x6f, 0x7b, 0x25, 0xf3, 0xf7, 0xa1, 0x4e, 0x63, 0x77, 0x13, 0x78,
	0xfe, 0x14, 0xe0, 0x7f, 0xdc, 0x42, 0x0f, 0xfe, 0x6c, 0x42, 0xfb, 0xa8, 0x50, 0x17, 0x67, 0x98,
	0xbf, 0x88, 0xcf, 0x91, 0x7d, 0x02, 0xed, 0xef, 0x31, 0x8f, 0x9f, 0x5f, 0x99, 0x67, 0xc8, 0xbe,
	0x1a, 0xa4, 0xe9, 0xed, 0x0e, 0xcc, 0xd3, 0x36, 0x98, 0x3e, 0x6d, 0x83, 0x27, 0xfa, 0x69, 0xe3,
	0x0e, 0xfb, 0x14, 0x3a, 0x43, 0x54, 0x73, 0xcf, 0xd3, 0xf5, 0xf0, 0x7b, 0x8b, 0x9a, 0xd2, 0x95,
	0x3b, 0xec, 0x18, 0x76, 0x86, 0xa8, 0x66, 0xc9, 0x1d, 0x5f, 0x9d, 0x84, 0xac, 0x6b, 0xfc, 0xcb,
	0x47, 0xf2, 0x24, 0xfc, 0xa6, 0xc0, 0xfc, 0xaa, 0x77, 0xd7, 0x42, 0x99, 0x05, 0x70, 0x87, 0x7d,
	0x0e, 0xdd, 0xaf, 0x62, 0x69, 0x81, 0x48, 0x33, 0x9b, 0xcb, 0x61, 0x76, 0x97, 0x5f, 0x31, 0xee,
	0xb0, 0x2f, 0x61, 0x4f, 0xe3, 0x9c, 0x52, 0x99, 0x66, 0x68, 0xb7, 0x03, 0x7b, 0x08, 0x9b, 0x43,
	0x54, 0xd4, 0xe2, 0x15, 0x39, 0x5d, 0xdb, 0x42, 0xdc, 0x61, 0x43, 0xe8, 0xd0, 0xe2, 0xd2, 0x5c,
	0xca, 0xe5, 0xd5, 0x9b, 0x0b, 0xa6, 0xd0, 0x1f, 0x62, 0x75, 0xa1, 0xdd, 0xe6, 0x28, 0x58, 0x0b,
	0x8f, 0x3b, 0xec, 0x08, 0x3a, 0x33, 0x8c, 0xdb, 0x65, 0xf1, 0x08, 0xb6, 0x87, 0xa8, 0xca, 0x9b,
	0xb0, 0x22, 0x8f, 0x25, 0x8b, 0x9e, 0x0a, 0xba, 0x53, 0x65, 0x52, 0xbd, 0x12, 0xab, 0x72, 0xf1,
	0x16, 0x73, 0x99, 0x46, 0x71, 0x87, 0x3d, 0x86, 0x1d, 0x1b, 0xe7, 0x76, 0xf9, 0x0c, 0x61, 0x5b,
	0x83, 0xd0, 0x6a, 0x32, 0x08, 0xbb, 0x73, 0x08, 0xcf, 0x82, 0x04, 0x0d, 0xc6, 0xfe, 0x8a, 0x4d,
	0xc6, 0x1d, 0xf6, 0x11, 0xb4, 0x87, 0x48, 0xa3, 0xb1, 0xa2, 0x2a, 0x8b, 0xef, 0x32, 0x77, 0xd8,
	0x13, 0xd8, 0xae, 0x4a, 0x62, 0x08, 0xac, 0xaa, 0xc7, 0xdd, 0xc5, 0x7a, 0x4c, 0x3f, 0xff, 0x05,
	0xb0, 0xf2, 0xf3, 0xf6, 0xef, 0xc9, 0x72, 0x16, 0xbd, 0x05, 0x16, 0x72, 0xee, 0xf2, 0x3c, 0x83,
	0xb7, 0x2a, 0x2e, 0x67, 0x41, 0x82, 0xff, 0x71, 0xee, 0x8f, 0x9b, 0x3f, 0x36, 0xb4, 0x36, 0x1b,
	0x8f, 0x1b, 0xb4, 0x2c, 0x3e, 0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x34, 0x5c, 0x70, 0x95, 0x33,
	0x0b, 0x00, 0x00,
}
