// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package workerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallTaskReq struct {
	TaskCodename         string   `protobuf:"bytes,1,opt,name=task_codename,json=taskCodename,proto3" json:"task_codename,omitempty"`
	TaskUniqueId         string   `protobuf:"bytes,2,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Arguments            []byte   `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Timeout              int64    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Caller               string   `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallTaskReq) Reset()         { *m = CallTaskReq{} }
func (m *CallTaskReq) String() string { return proto.CompactTextString(m) }
func (*CallTaskReq) ProtoMessage()    {}
func (*CallTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *CallTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallTaskReq.Unmarshal(m, b)
}
func (m *CallTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallTaskReq.Marshal(b, m, deterministic)
}
func (m *CallTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallTaskReq.Merge(m, src)
}
func (m *CallTaskReq) XXX_Size() int {
	return xxx_messageInfo_CallTaskReq.Size(m)
}
func (m *CallTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallTaskReq proto.InternalMessageInfo

func (m *CallTaskReq) GetTaskCodename() string {
	if m != nil {
		return m.TaskCodename
	}
	return ""
}

func (m *CallTaskReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *CallTaskReq) GetArguments() []byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *CallTaskReq) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CallTaskReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CallTaskReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type KillTaskReq struct {
	TaskUniqueId         string   `protobuf:"bytes,1,opt,name=task_unique_id,json=taskUniqueId,proto3" json:"task_unique_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillTaskReq) Reset()         { *m = KillTaskReq{} }
func (m *KillTaskReq) String() string { return proto.CompactTextString(m) }
func (*KillTaskReq) ProtoMessage()    {}
func (*KillTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *KillTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillTaskReq.Unmarshal(m, b)
}
func (m *KillTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillTaskReq.Marshal(b, m, deterministic)
}
func (m *KillTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillTaskReq.Merge(m, src)
}
func (m *KillTaskReq) XXX_Size() int {
	return xxx_messageInfo_KillTaskReq.Size(m)
}
func (m *KillTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KillTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_KillTaskReq proto.InternalMessageInfo

func (m *KillTaskReq) GetTaskUniqueId() string {
	if m != nil {
		return m.TaskUniqueId
	}
	return ""
}

func (m *KillTaskReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*CallTaskReq)(nil), "workerpb.CallTaskReq")
	proto.RegisterType((*KillTaskReq)(nil), "workerpb.KillTaskReq")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0x59, 0xab, 0xb5, 0x7d, 0x8d, 0x82, 0x0b, 0x96, 0xa5, 0x7a, 0x08, 0xd5, 0x43, 0x4e,
	0x5b, 0xd0, 0x93, 0xe7, 0xe2, 0x41, 0x3c, 0x19, 0x15, 0x8f, 0x65, 0x93, 0x3c, 0x43, 0xc8, 0x9f,
	0x4d, 0x37, 0x1b, 0xc5, 0x8f, 0xe0, 0x17, 0xf3, 0x73, 0xc9, 0x6e, 0xba, 0x24, 0xa0, 0x3d, 0xbe,
	0x61, 0x66, 0x98, 0xf7, 0x03, 0xef, 0x53, 0xaa, 0x1c, 0x15, 0xaf, 0x95, 0xd4, 0x92, 0x4e, 0xba,
	0xab, 0x8e, 0x16, 0x17, 0xa9, 0x94, 0x69, 0x81, 0x2b, 0xab, 0x47, 0xed, 0xfb, 0x0a, 0xcb, 0x5a,
	0x7f, 0x75, 0xb6, 0xe5, 0x0f, 0x81, 0xd9, 0x5a, 0x14, 0xc5, 0x8b, 0x68, 0xf2, 0x10, 0xb7, 0xf4,
	0x0a, 0x4e, 0xb4, 0x68, 0xf2, 0x4d, 0x2c, 0x13, 0xac, 0x44, 0x89, 0x8c, 0xf8, 0x24, 0x98, 0x86,
	0x9e, 0x11, 0xd7, 0x3b, 0x8d, 0x5e, 0xc3, 0xa9, 0x35, 0xb5, 0x55, 0xb6, 0x6d, 0x71, 0x93, 0x25,
	0xec, 0xa0, 0x77, 0xbd, 0x5a, 0xf1, 0x21, 0xa1, 0x97, 0x30, 0x15, 0x2a, 0x6d, 0x4b, 0xac, 0x74,
	0xc3, 0x46, 0x3e, 0x09, 0xbc, 0xb0, 0x17, 0x28, 0x83, 0x63, 0x9d, 0x95, 0x28, 0x5b, 0xcd, 0x0e,
	0x7d, 0x12, 0x8c, 0x42, 0x77, 0xd2, 0x39, 0x8c, 0x63, 0x51, 0x14, 0xa8, 0xd8, 0x91, 0x6d, 0xdd,
	0x5d, 0xa6, 0xcf, 0x58, 0x1a, 0x2d, 0xca, 0x9a, 0x8d, 0x6d, 0xa6, 0x17, 0x96, 0x4f, 0x30, 0x7b,
	0xcc, 0xfa, 0x3f, 0xfe, 0x4e, 0x24, 0xff, 0x4f, 0xdc, 0x5f, 0x79, 0xf3, 0x4d, 0xe0, 0xcc, 0xf4,
	0xbd, 0x59, 0x92, 0xcf, 0xa8, 0x3e, 0xb2, 0x18, 0xe9, 0x1d, 0x4c, 0x1c, 0x30, 0x7a, 0xce, 0x1d,
	0x65, 0x3e, 0x80, 0xb8, 0x98, 0xf3, 0x0e, 0x39, 0x77, 0xc8, 0xf9, 0xbd, 0x41, 0x6e, 0xa2, 0x6e,
	0xe3, 0x30, 0x3a, 0xd8, 0xbd, 0x2f, 0x1a, 0x8d, 0xed, 0x7d, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0xbe, 0x24, 0x3a, 0xe5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskWorkerServiceClient is the client API for TaskWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskWorkerServiceClient interface {
	// CallTask 调用任务
	CallTask(ctx context.Context, in *CallTaskReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// KillTask 结束任务
	KillTask(ctx context.Context, in *KillTaskReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type taskWorkerServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskWorkerServiceClient(cc *grpc.ClientConn) TaskWorkerServiceClient {
	return &taskWorkerServiceClient{cc}
}

func (c *taskWorkerServiceClient) CallTask(ctx context.Context, in *CallTaskReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/workerpb.TaskWorkerService/CallTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskWorkerServiceClient) KillTask(ctx context.Context, in *KillTaskReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/workerpb.TaskWorkerService/KillTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskWorkerServiceServer is the server API for TaskWorkerService service.
type TaskWorkerServiceServer interface {
	// CallTask 调用任务
	CallTask(context.Context, *CallTaskReq) (*emptypb.Empty, error)
	// KillTask 结束任务
	KillTask(context.Context, *KillTaskReq) (*emptypb.Empty, error)
}

func RegisterTaskWorkerServiceServer(s *grpc.Server, srv TaskWorkerServiceServer) {
	s.RegisterService(&_TaskWorkerService_serviceDesc, srv)
}

func _TaskWorkerService_CallTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskWorkerServiceServer).CallTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerpb.TaskWorkerService/CallTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskWorkerServiceServer).CallTask(ctx, req.(*CallTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskWorkerService_KillTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskWorkerServiceServer).KillTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerpb.TaskWorkerService/KillTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskWorkerServiceServer).KillTask(ctx, req.(*KillTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskWorkerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workerpb.TaskWorkerService",
	HandlerType: (*TaskWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTask",
			Handler:    _TaskWorkerService_CallTask_Handler,
		},
		{
			MethodName: "KillTask",
			Handler:    _TaskWorkerService_KillTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
